app/Http/routes.php
Route::get('/bell_notifications' , 'SampleController@bell_notifications');

Route::get('/video_notification' , 'SampleController@video_notification');

Route::get('/upload_videoUI' , 'SampleController@upload_video');

// Unused Sample Routes

Route::get('/addIndex', 'ApplicationController@addIndex')->name('addIndex');

Route::get('/addAll', 'ApplicationController@addAllVideoToEs')->name('addAll');

Route::post('select/sub_category' , 'ApplicationController@select_sub_category')->name('select.sub_category');

Route::post('select/genre' , 'ApplicationController@select_genre')->name('select.genre');


// Chat Message save


Route::get('message/save' , 'ApplicationController@message_save')->name('message.save');


// Cron jobs

Route::get('/automatic/renewal', 'ApplicationController@automatic_renewal')->name('automatic.renewal');

// Application Routes

Route::get('/generate/index' , 'ApplicationController@generate_index');

Route::get('/payment/failure' , 'ApplicationController@payment_failure')->name('payment.failure');

Route::get('/email/verification' , 'ApplicationController@email_verify')->name('email.verify');

// Installation

Route::get('/install/configure', 'InstallationController@install')->name('installTheme');

Route::get('/system/check', 'InstallationController@system_check_process')->name('system-check');

Route::post('/install/theme', 'InstallationController@theme_check_process')->name('install.theme');

Route::post('/install/settings', 'InstallationController@settings_process')->name('install.settings');

Route::get('/user_session_language/{lang}', 'ApplicationController@set_session_language')->name('user_session_language');

Route::get('/user/searchall' , 'ApplicationController@search_video')->name('search');

Route::any('/user/search' , 'ApplicationController@search_all')->name('search-all');

// Social Login

Route::post('/social', array('as' => 'SocialLogin' , 'uses' => 'SocialAuthController@redirect'));

Route::get('/callback/{provider}', 'SocialAuthController@callback');

// Referral link generate

Route::get('/rc/{referral_code}', 'UserController@referrals_signup')->name('referrals_signup');

// Embed Links

Route::get('/embed', 'ApplicationController@embed_video')->name('embed_video');

// Admin to users login

Route::get('/master/login', 'UserController@master_login')->name('master.login');

// CRON

Route::get('/publish/video', 'ApplicationController@cron_publish_video')->name('publish');

Route::get('/notification/payment', 'ApplicationController@send_notification_user_payment')->name('notification.user.payment');

Route::get('/payment/expiry', 'ApplicationController@user_payment_expiry')->name('user.payment.expiry');

Route::get('cron_delete_video', 'ApplicationController@cron_delete_video');
    
// Static Pages

Route::get('/privacy', 'UserApiController@privacy')->name('user.privacy');

Route::get('/help', 'UserApiController@help')->name('user.help');

Route::get('/terms_condition', 'UserApiController@terms')->name('user.terms');

Route::get('/about', 'ApplicationController@about')->name('user.about');

Route::get('/privacy_policy', 'ApplicationController@privacy')->name('user.privacy_policy');

Route::get('/terms', 'ApplicationController@terms')->name('user.terms-condition');

Route::get('page_view/{id}', 'UserController@page_view')->name('page_view');

Route::get('/admin/check_role', 'NewAdminController@check_role');

Route::group(['prefix' => 'admin' , 'as' => 'admin.'], function() {

    Route::get('login', 'Auth\AdminAuthController@showLoginForm')->name('login');

    Route::post('login', 'Auth\AdminAuthController@login')->name('login.post');

    Route::get('logout', 'Auth\AdminAuthController@logout')->name('logout');

    Route::get('secure', 'AdminController@secure')->name('secure');

    // Registration Routes...

    Route::get('register', 'Auth\AdminAuthController@showRegistrationForm');

    Route::post('register', 'Auth\AdminAuthController@register');

    // Password Reset Routes...
    Route::get('password/reset/{token?}', 'Auth\AdminPasswordController@showResetForm');

    Route::post('password/email', 'Auth\AdminPasswordController@sendResetLinkEmail');

    Route::post('password/reset', 'Auth\AdminPasswordController@reset');

    Route::get('/payment/failure' , 'ApplicationController@payment_failure')->name('payment.failure');

    // Videos

    Route::get('/live_videos', 'AdminController@live_videos')->name('live-videos.index');

    Route::get('/live-videos/list', 'AdminController@live_videos_history')->name('live-videos.history');

    Route::get('/live-videos/view/{id}', 'AdminController@live_videos_view')->name('live-videos.view');

    Route::get('/live-videos/payments', 'AdminController@live_video_payments')->name('live-videos.payments');


    // Exports tables

    Route::get('/users/export/', 'AdminExportController@users_export')->name('users.export');

    Route::get('/channels/export/', 'AdminExportController@channels_export')->name('channels.export');

    Route::get('/videos/export/', 'AdminExportController@videos_export')->name('video_tapes.export');

    Route::get('/subscription/payment/export/', 'AdminExportController@subscription_export')->name('subscription.export');

    Route::get('/payperview/payment/export/', 'AdminExportController@payperview_export')->name('payperview.export');

    Route::get('/live-videos/export/', 'AdminExportController@livevideos_export')->name('live-videos.export');

    Route::get('/live-video/payment/export/', 'AdminExportController@livevideo_payment_export')->name('livevideo-payment.export');

    // Languages

    Route::get('/languages/index', 'LanguageController@languages_index')->name('languages.index'); 

    Route::get('/languages/download/', 'LanguageController@languages_download')->name('languages.download'); 

    Route::get('/languages/create', 'LanguageController@languages_create')->name('languages.create');
    
    Route::get('/languages/edit', 'LanguageController@languages_edit')->name('languages.edit');

    Route::get('/languages/status', 'LanguageController@languages_status_change')->name('languages.status');   

    Route::post('/languages/save', 'LanguageController@languages_save')->name('languages.save');

    Route::get('/languages/delete', 'LanguageController@languages_delete')->name('languages.delete');

    Route::get('/languages/set_default', 'LanguageController@languages_set_default')->name('languages.set_default');


    // ============= branch v4.0-admin-coderevamp ================

    Route::get('/', 'NewAdminController@dashboard')->name('dashboard');

    // New Admin user methods

    Route::get('/users/index', 'NewAdminController@users_index')->name('users.index');

    Route::get('/users/create', 'NewAdminController@users_create')->name('users.create');

    Route::get('/users/edit', 'NewAdminController@users_edit')->name('users.edit');
    
    Route::post('/users/save', 'NewAdminController@users_save')->name('users.save');

    Route::get('/users/view', 'NewAdminController@users_view')->name('users.view');

    Route::get('/users/delete', 'NewAdminController@users_delete')->name('users.delete');

    Route::get('/users/status','NewAdminController@users_status_change')->name('users.status');

    Route::get('/users/verify/', 'NewAdminController@users_verify_status')->name('users.verify');

    Route::get('/users/channels/', 'NewAdminController@users_channels')->name('users.channels');

    Route::get('/users/history/', 'NewAdminController@users_history')->name('users.history');

    Route::get('users/type/','NewAdminController@users_type_list')->name('users.type');

    Route::get('/users/history/delete/', 'NewAdminController@users_history_delete')->name('users.history.delete');

    Route::get('/users/wishlist/', 'NewAdminController@users_wishlist')->name('users.wishlist');

    Route::get('/users/wishlist/delete/', 'NewAdminController@users_wishlist_delete')->name('users.wishlist.delete');    

    Route::get('/users/playlist/index', 'NewAdminController@playlists_index')->name('users.playlist.index');
    
    Route::get('/users/playlist/delete', 'NewAdminController@playlists_delete')->name('users.playlist.delete');

    Route::get('/users/playlist/view', 'NewAdminController@playlist_video')->name('users.playlist.view'); 

    Route::get('/users/playlist/video/remove', 'NewAdminController@playlists_video_remove')->name('users.playlist.video.delete');
    
    Route::get('/users/referral/index', 'NewAdminController@users_index')->name('users.referral.index');

    //User Subscriptions

    Route::get('/users/subscriptions/', 'NewAdminController@users_subscriptions')->name('users.subscriptions.plans');

    Route::get('/users/subscriptions/save', 'NewAdminController@users_subscription_save')->name('users.subscription.save');

    // New Admin Channeles methods begins

    Route::get('/channels', 'NewAdminController@channels_index')->name('channels.index');

    Route::get('/channels/create', 'NewAdminController@channels_create')->name('channels.create');

    Route::get('/channels/edit', 'NewAdminController@channels_edit')->name('channels.edit');    
    Route::post('/channels/save', 'NewAdminController@channels_save')->name('channels.save');

    Route::get('/channels/videos', 'NewAdminController@channels_videos')->name('channels.videos');

    Route::get('/channels/delete', 'NewAdminController@channels_delete')->name('channels.delete');

    Route::get('/channels/view', 'NewAdminController@channels_view')->name('channels.view');

    Route::get('/channels/status/change', 'NewAdminController@channels_status_change')->name('channels.status');

    Route::get('/channels/subscribers', 'NewAdminController@channels_subscribers')->name('channels.subscribers');

    Route::get('/channel/playlists/index', 'NewAdminController@channels_playlists_index')->name('channels.playlists.index');

app/Channel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Helpers\Helper;

class Channel extends Model
{
    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */

    public function scopeBaseResponse($query) {

        return $query->leftJoin('users', 'channels.user_id', '=', 'users.id')
                    ->select('channels.id as channel_id', 
                        'channels.user_id as user_id', 
                        'channels.name as channel_name', 
                        'channels.description as channel_description', 
                        'channels.picture as channel_image', 
                        'channels.cover as channel_cover', 
                        'users.name as channel_owner_name',
                        'users.picture as channel_owner_picture',
                        'channels.is_approved as is_admin_approved', 
                        'channels.status as channel_status', 
                        'channels.created_at', 
                        'channels.updated_at'
                    );

    }

    public function videoTape() {
        return $this->hasMany('App\VideoTape')->leftJoin('channels' , 'video_tapes.channel_id' , '=' , 'channels.id')->videoResponse();
    }

    /**
     * Get the video record associated with the flag.
     */
    public function getUser()
    {
        return $this->hasOne('App\User', 'id', 'user_id');
    }
    
    /**
     * Save the unique ID 
     *
     *
     */
    public function setUniqueIdAttribute($value){

        $this->attributes['unique_id'] = uniqid(str_replace(' ', '-', $value));

    }

    public function getVideos() {
        return $this->hasMany('App\VideoTape')->leftJoin('channels' , 'video_tapes.channel_id' , '=' , 'channels.id')->videoResponse()->where('status', DEFAULT_TRUE)->where('is_approved', DEFAULT_TRUE);
    }

    public function getVideoTape() {
        return $this->hasMany('App\VideoTape');
    }

    public function getChannelSubscribers() {
        return $this->hasMany('App\ChannelSubscription');
    }

    public function getPlaylist() {
        return $this->hasMany('App\Playlist');
    }

    public function getBellNotifications() {

         return $this->hasMany('App\BellNotification', 'channel_id', 'id');

    }

    /**
     * Boot function for using with User Events
     *
     * @return void
     */

    public static function boot()
    {
        //execute the parent's boot method 
        parent::boot();

        //delete your related models here, for example
        static::deleting(function($model)
        {

            if($model->picture) {
                Helper::delete_picture($model->picture, "/uploads/channels/picture/");
            }

            if($model->cover) {
                Helper::delete_picture($model->cover, "/uploads/channels/cover/");
            }

            if (count($model->getVideoTape) > 0) {

                foreach ($model->getVideoTape as $key => $value) {

                    Helper::delete_picture($value->video, "/uploads/videos/");

                    Helper::delete_picture($value->subtitle, "/uploads/subtitles/"); 

                    if ($value->banner_image) {

                        Helper::delete_picture($value->banner_image, "/uploads/images/");
                    }

                    Helper::delete_picture($value->default_image, "/uploads/images/");

                    if ($value->video_path) {

                        $explode = explode(',', $value->video_path);

                        if (count($explode) > 0) {

                            foreach ($explode as $key => $exp) {

                                Helper::delete_picture($exp, "/uploads/videos/");

                            }
                        }
                    }

                   $value->delete();    

                }

            }

            if (count($model->getChannelSubscribers) > 0) {

                foreach ($model->getChannelSubscribers as $key => $value) {

                   $value->delete();    

                }

            }

            if (count($model->getPlaylist) > 0) {

                foreach ($model->getPlaylist as $key => $playlist) {

                   $playlist->delete();    
                }
            }

            if (count($model->getBellNotifications) > 0) {

                foreach ($model->getBellNotifications as $key => $value) {

                   $value->delete();    

                }            

            }


        }); 

    }

}

resources/views/new_admin/channels/create.blade.php
@extends('layouts.admin')

@section('title', tr('add_channel'))

@section('content-header', tr('add_channel'))

@section('breadcrumb')
    <li><a href="{{route('admin.channels.index')}}"><i class="fa fa-suitcase"></i> {{tr('channels')}}</a></li>
    <li class="active">{{tr('add_channel')}}</li>
@endsection

@section('content')

<div class="row">

    <div class="col-md-12">

        @include('notification.notify')

        <div class="box box-primary">

            <div class="box-header label-primary">
                <b style="font-size:18px;">{{ tr('add_channel') }}</b>
                <a href="{{ route('admin.channels.index') }}" class="btn btn-default pull-right">{{ tr('channels') }}</a>
            </div>

			@include('new_admin.channels._form')

        </div>

    </div>

</div>



@endsection

@section('scripts')
    <script src="https://cdn.ckeditor.com/4.5.5/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'description' );
    </script>
@endsection

resources/views/new_admin/channels/index.blade.php
@extends('layouts.admin') 

@section('title', tr('channels')) 

@section('content-header') 

@if(isset($user)) 

	<span class="text-green"> {{ $user->name }} </span>- 

@endif {{ tr('channels') }}

@endsection 

@section('breadcrumb')
	 
	<li class="active"><i class="fa fa-suitcase"></i> {{ tr('channels') }}</li>
@endsection 

@section('content')

<div class="row">

    <div class="col-xs-12">

        @include('notification.notify')

        <div class="box box-primary">

            <div class="box-header label-primary">

                <b style="font-size:18px;">{{ tr('channels') }}</b>
                <a href="{{ route('admin.channels.create') }}" class="btn btn-default pull-right">{{ tr('add_channel') }}</a>

                <!-- EXPORT OPTION START -->

                @if(count($channels) > 0 )

                <ul class="admin-action btn btn-default pull-right" style="margin-right: 20px">
                    
                    <li class="dropdown">

                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
	                      {{ tr('export') }} <span class="caret"></span>
	                    </a>

                        <ul class="dropdown-menu">
                            <li role="presentation">
                                <a role="menuitem" tabindex="-1" href="{{ route('admin.channels.export' , ['format' => 'xlsx']) }}">
                                    <span class="text-red"><b>{{ tr('excel_sheet') }}</b></span>
                                </a>
                            </li>

                            <li role="presentation">
                                <a role="menuitem" tabindex="-1" href="{{ route('admin.channels.export' , ['format' => 'csv']) }}">
                                    <span class="text-blue"><b>{{ tr('csv') }}</b></span>
                                </a>
                            </li>
                        </ul>

                    </li>

                </ul>

                @endif

                <!-- EXPORT OPTION END -->

            </div>
            <div class="box-body table-responsive">

                @if(count($channels) > 0)

                <table id="example1" class="table table-bordered table-striped">

                    <thead>
                        <tr>
                            <th>{{ tr('id') }}</th>
                            <th>{{ tr('channel') }}</th>
                            <th>{{ tr('user_name') }}</th>
                            <th>{{ tr('no_of_videos') }}</th>
                            <th>{{ tr('subscribers') }}</th>
                            <th>{{ tr('amount') }}</th>
                            <th>{{ tr('status') }}</th>
                            <th>{{ tr('action') }}</th>
                        </tr>
                    </thead>

                    <tbody>

                        @foreach($channels as $i => $channel_details)

	                        <tr>
	                            <td>{{ $i+1 }}</td>

	                            <td><a target="_blank" href="{{ route('admin.channels.view',['channel_id' => $channel_details->id] ) }}">{{ $channel_details->name }}</a></td>

	                            <td><a target="_blank" href="{{ route('admin.users.view', ['user_id' => $channel_details->user_id] ) }}">{{ $channel_details->getUser ? $channel_details->getUser->name : '' }}</a></td>

	                            <td><a target="_blank" href="{{ route('admin.channels.videos', ['channel_id'=> $channel_details->id] ) }}">{{ $channel_details->get_video_tape_count }}</a></td>

	                            <td><a target="_blank" href="{{ route('admin.channels.subscribers', ['channel_id' => $channel_details->id]) }}">{{ $channel_details->get_channel_subscribers_count }}</a></td>

	                            <td>{{ formatted_amount(getAmountBasedChannel($channel_details->id)) }}</td>

	                            <td>
	                                @if($channel_details->is_approved)
	                                <span class="label label-success">{{ tr('approved') }}</span> @else
	                                <span class="label label-warning">{{ tr('pending') }}</span> @endif
	                            </td>

	                            <td>
	                                <ul class="admin-action btn btn-default">

	                                    <li class="{{ $i <=2 ? 'dropdown' : 'dropup' }}">

	                                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
									           {{ tr('action') }} <span class="caret"></span>
									        </a>
	                                        <ul class="dropdown-menu">

                                                <li role="presentation">
                                                    <a role="menuitem" tabindex="-1" href="{{ route('admin.channels.view',['channel_id' => $channel_details->id] ) }}">{{tr('view')}}</a>
                                                </li>

                                                @if(Setting::get('admin_delete_control') == YES)
                                                
                                                    <li role="presentation"><a role="button" href="javascript:;" class="btn disabled" style="text-align: left">{{ tr('edit') }}</a></li> 

                                                    <li role="presentation"><a role="button"  href="javascript:;" class="btn disabled" style="text-align: left" onclick="return confirm(&quot;{{ tr('admin_channel_delete_confirmation', $channel_details->name) }}&quot;)" >{{ tr('delete') }}</a></li> 
                                                    
                                                @else

                                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="{{ route('admin.channels.edit' , ['channel_id' => $channel_details->id] ) }}">{{ tr('edit') }}</a></li> 

                                                    <li role="presentation"><a role="menuitem" tabindex="-1" onclick="return confirm(&quot;{{ tr('admin_channel_delete_confirmation', $channel_details->name) }}&quot;)" href="{{ route('admin.channels.delete' , ['channel_id' => $channel_details->id] ) }}">{{ tr('delete') }}</a></li>

                                                @endif
                                          
	                                            <li class="divider" role="presentation"></li>

                                                <li role="presentation">
    	                                            @if($channel_details->is_approved == APPROVED)
    	                                            	<a role="menuitem" tabindex="-1" href="{{ route('admin.channels.status' , ['channel_id' => $channel_details->id] ) }}" onclick="return confirm(&quot;{{ tr('admin_channel_decline_notes', $channel_details->name) }}&quot;)"> {{ tr('decline') }}</a>
    	                                            @else
    	                                            	<a role="menuitem" tabindex="-1" href="{{ route('admin.channels.status' , ['channel_id' => $channel_details->id] ) }}" onclick="return confirm(&quot;{{ tr('admin_channel_approve_notes', $channel_details->name) }}&quot;)"> {{ tr('approve') }}</a>
    	                                            @endif
                                                </li>

                                                <li role="presentation"><a role="menuitem" tabindex="-1" href="{{ route('admin.channels.playlists.index' , ['channel_id' => $channel_details->id] ) }}">{{ tr('playlist') }}</a></li>

	                                        </ul>

	                                    </li>

	                                </ul>

	                            </td>

	                        </tr>

                        @endforeach

                    </tbody>

                </table>

                @else

                	<h3 class="no-result">{{ tr('no_result_found') }}</h3> 

                @endif

            </div>

        </div>

    </div>

</div>


@endsection

resources/views/new_admin/channels/playlist_create.blade.php
@extends('layouts.admin')

@section('title', tr('add_playlist'))

@section('content-header', tr('add_playlist'))

@section('breadcrumb')
    <li><a href="{{route('admin.channels.index')}}"><i class="fa fa-suitcase"></i> {{tr('channels')}}</a></li> 

   <li><a href="{{ route('admin.channels.view',['channel_id' => $channel_details->id] ) }}"><i class="fa fa-suitcase"></i> {{ $channel_details->name }}</a></li>

   <li class="active">{{tr('add_playlist')}}</li>

@endsection

@section('content')

<div class="row">

   <div class="col-md-12">

       @include('notification.notify')

       <div class="box box-primary">

           <div class="box-header label-primary">
               <b style="font-size:18px;">{{ tr('add_playlist') }}</b>
               <a href="{{ route('admin.channels.index') }}" class="btn btn-default pull-right">{{ tr('channels') }}</a>
           </div>

           @include('new_admin.channels._form_playlist')

       </div>

   </div>

</div>

@endsection

resources/views/new_admin/channels/playlist_videos.blade.php
@extends('layouts.admin')

@section('title', tr('playlist'))

@section('content-header') 

	{{ tr('playlist') }}

@endsection

@section('breadcrumb')
    <li ><i class="fa fa-suitcase"></i> <a href="{{ route('admin.channels.index')}}" > {{ tr('channels') }} </a></li>
	
	<li ><i class="fa fa-suitcase"></i> <a href="{{ route('admin.channels.view',['channel_id' => $channel_details])}}" >{{ $channel_details->name }}'s </a></li>
    
    <li><i class="fa fa-list"></i> <a href="{{ route('admin.channels.playlists.index', ['channel_id' =>  $channel_details->id]) }}">{{ tr('playlist') }}</a> </li>
    
    <li class="active"><i class="fa fa-video-camera"></i> {{ tr('playlist_videos') }}</li>
    
@endsection

@section('content')
	
	<div class="row">

        <div class="col-xs-12">
			
			@include('notification.notify')

          	<div class="box box-primary">

	          	<div class="box-header label-primary">
	                <b style="font-size:18px;">{{ tr('playlist') }}</b>
	            </div>
			<div class="col-xs-12 col-sm-12">
	            <div class="col-xs-4 col-sm-4 col-md-4 box-body">
	             	<b style="font-size:18px;">{{ tr('playlist') }} - <a href="{{route('admin.channels.playlists.view', ['playlist_id' => $playlist_details->id, 'channel_id' =>  $channel_details->id]) }}">{{ $playlist_details->title }}</a></b>
	            </div>  

	            <div class="col-xs-4 col-sm-4 col-md-4 box-body">
	             	<b style="font-size:18px;">{{ tr('channel') }} - <a href="#">{{ $channel_details->name }}</a></b>
	            </div>  

	            <div class="box-body col-xs-4 col-sm-4 col-md-4">
	             	<b style="font-size:18px;">{{ tr('total_videos') }} - <a href="#">{{ $playlist_details->total_videos }}</a></b>
	            </div>
	        </div>
	        <br>
	        <br>
	            <hr>

	            <div class="box-body table-responsive">

	            	@if(count($playlists_videos) > 0)

		              	<table id="example1" class="table table-bordered table-striped">

							<thead>
							    <tr>
							      	<th>{{ tr('id') }}</th>

							      	<th>{{ tr('videos') }}</th>
							      	
							      	<th>{{ tr('added_on') }}</th>
							      
							      	<th>{{ tr('action') }}</th>
							    </tr>
							</thead>

							<tbody>
								@foreach($playlists_videos as $i => $playlists_video_details)

								    <tr>
								      	<td>{{ $i+1 }}</td>
							      	
								      	<td>
								      		<a href="{{ route('admin.video_tapes.view' ,  ['video_tape_id' => $playlists_video_details->video_tape_id] ) }}">
								      		{{ $playlists_video_details->video_tape_title }}
								      		</a>
									    </td>
									    <td>
									    	{{$playlists_video_details->created_at}}
									    </td>

									    <td>

										    @if(Setting::get('admin_delete_control') == YES )

	          									<a href="javascript:;" onclick="return confirm(&quot;{{ tr('admin_user_playlist_delete_confirmation',$playlist_details->title) }}&quot;)" class="btn btn-danger" title="{{tr('delete')}}" ><b><i class="fa fa-trash"></i></b> 
	          									</a>	

	          								@else

												<a href="{{ route('admin.channels.playlist.video.delete', ['playlist_video_id' => $playlists_video_details->playlist_video_id] ) }}" onclick="return confirm(&quot;{{ tr('admin_channel_playlist_video_delete_confirmation', $playlists_video_details->video_tape_title) }}&quot;)" class="btn btn-danger" title="{{tr('delete')}}" ><b><i class="fa fa-trash"></i></b> 
	          									</a>

	          								@endif

								      	</td>

								    </tr>
								@endforeach

							</tbody>

						</table>

					@else
						<h3 class="no-result">{{ tr('no_playlist_found') }}</h3>
					@endif

	            </div>

          	</div>

        </div>

    </div>

@endsection

resources/views/new_admin/channels/subscribers.blade.php
@extends('layouts.admin')

@section('title', tr('channels'))

@section('content-header')

@if(isset($user)) 
	
	<span class="text-green"> {{ $user->name }} </span>- 

@endif 

{{ tr('channels') }} 

@if($channel_details)

    - <a href="{{ route('admin.channels.view',['channel_id' =>$channel_details->id ]) }}">{{ $channel_details->name }}</a>

@endif

@endsection

@section('breadcrumb')
     
    <li><a href="{{ route('admin.channels.index') }}"><i class="fa fa-suitcase"></i> {{ tr('channels') }}</a></li>
    <li class="active"><i class="fa fa-suitcase"></i> {{ tr('subscribers') }}</li>
@endsection

@section('content')

	@include('notification.notify')

	<div class="row">

        <div class="col-xs-12">

          	<div class="box box-primary">
          	
	          	<div class="box-header label-primary">
	                <b style="font-size:18px;">{{ tr('subscribers') }}</b>
	            </div>
	            
	            <div class="box-body">

	            	@if(count($channel_subscriptions) > 0)

		              	<table id="example1" class="table table-bordered table-striped">

							<thead>
							    <tr>
							      	<th>{{ tr('id') }}</th>
							      	<th>{{ tr('channel') }}</th>
							      	<th>{{ tr('picture') }}</th>
							      	<th>{{ tr('subscriber_name') }}</th>
							  	  	<th>{{ tr('action') }}</th>
							    </tr>
							</thead>

							<tbody>

								@foreach($channel_subscriptions as $i => $channel_subscription_details)

								    <tr>
								      	<td>{{ $i+1 }}</td>

								      	<td><a target="_blank" href="{{ route('admin.channels.view', ['channel_id' => $channel_subscription_details->channel_id] ) }}">{{ $channel_subscription_details->getChannel ? $channel_subscription_details->getChannel->name : '' }}</a></td>
								      	
								      	<td>
								      		@if($channel_subscription_details->getChannel)
		                                	<img style="height: 30px;" src="{{ $channel_subscription_details->getChannel->picture }}">
		                                	@endif
		                            	</td>	                           

		                            	<td><a target="_blank" href="{{ route('admin.users.view', ['user_id' => $channel_subscription_details->user_id] ) }}">{{ $channel_subscription_details->getUser ? $channel_subscription_details->getUser->name : '' }}</a></td>
		                            	
								     	<td>	
								     		@if($channel_subscription_details->getUser)
								     			<a href="{{ route('admin.users.view', ['user_id' =>  $channel_subscription_details->getUser ? $channel_subscription_details->getUser-> id: ''] ) }}" class="btn btn-success">{{ tr('view_user') }}</a>
								     		@else
								     			-
								     		@endif            							
								      	</td>

								    </tr>

								@endforeach

							</tbody>

						</table>

					@else
						<h3 class="no-result">{{ tr('no_result_found') }}</h3>
					@endif
					
	            </div>

          	</div>

        </div>

    </div>

@endsection