app/Http/routes.php
<?php  

use Illuminate\Support\Facades\Redis;


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/clear-cache', function() {

    $exitCode = Artisan::call('config:cache');

    return back();

})->name('clear-cache');


// Generral configuration routes 

Route::post('project/configurations' , 'ApplicationController@configuration_site');

Route::get('pages/list' , 'ApplicationController@static_pages_api');

Route::get('video_tapes_auto_clear_cron' , 'ApplicationController@video_tapes_auto_clear_cron');

Route::get('demo_credential_cron' , 'ApplicationController@demo_credential_cron');

// UI

Route::get('/bell_notifications' , 'SampleController@bell_notifications');

Route::get('/video_notification' , 'SampleController@video_notification');

Route::get('/upload_videoUI' , 'SampleController@upload_video');

// Unused Sample Routes

Route::get('/addIndex', 'ApplicationController@addIndex')->name('addIndex');

Route::get('/addAll', 'ApplicationController@addAllVideoToEs')->name('addAll');

Route::post('select/sub_category' , 'ApplicationController@select_sub_category')->name('select.sub_category');

Route::post('select/genre' , 'ApplicationController@select_genre')->name('select.genre');


// Chat Message save


Route::get('message/save' , 'ApplicationController@message_save')->name('message.save');


// Cron jobs

Route::get('/automatic/renewal', 'ApplicationController@automatic_renewal')->name('automatic.renewal');

// Application Routes

Route::get('/generate/index' , 'ApplicationController@generate_index');

Route::get('/payment/failure' , 'ApplicationController@payment_failure')->name('payment.failure');

Route::get('/email/verification' , 'ApplicationController@email_verify')->name('email.verify');

// Installation

Route::get('/install/configure', 'InstallationController@install')->name('installTheme');

Route::get('/system/check', 'InstallationController@system_check_process')->name('system-check');

Route::post('/install/theme', 'InstallationController@theme_check_process')->name('install.theme');

Route::post('/install/settings', 'InstallationController@settings_process')->name('install.settings');

Route::get('/user_session_language/{lang}', 'ApplicationController@set_session_language')->name('user_session_language');

Route::get('/user/searchall' , 'ApplicationController@search_video')->name('search');

Route::any('/user/search' , 'ApplicationController@search_all')->name('search-all');

// Social Login

Route::post('/social', array('as' => 'SocialLogin' , 'uses' => 'SocialAuthController@redirect'));

Route::get('/callback/{provider}', 'SocialAuthController@callback');

// Referral link generate

Route::get('/rc/{referral_code}', 'UserController@referrals_signup')->name('referrals_signup');

// Embed Links

Route::get('/embed', 'ApplicationController@embed_video')->name('embed_video');

// Admin to users login

Route::get('/master/login', 'UserController@master_login')->name('master.login');

// CRON

Route::get('/publish/video', 'ApplicationController@cron_publish_video')->name('publish');

Route::get('/notification/payment', 'ApplicationController@send_notification_user_payment')->name('notification.user.payment');

Route::get('/payment/expiry', 'ApplicationController@user_payment_expiry')->name('user.payment.expiry');

Route::get('cron_delete_video', 'ApplicationController@cron_delete_video');
    
// Static Pages

Route::get('/privacy', 'UserApiController@privacy')->name('user.privacy');

Route::get('/help', 'UserApiController@help')->name('user.help');

Route::get('/terms_condition', 'UserApiController@terms')->name('user.terms');

Route::get('/about', 'ApplicationController@about')->name('user.about');

Route::get('/privacy_policy', 'ApplicationController@privacy')->name('user.privacy_policy');

Route::get('/terms', 'ApplicationController@terms')->name('user.terms-condition');

Route::get('page_view/{id}', 'UserController@page_view')->name('page_view');

Route::get('/admin/check_role', 'NewAdminController@check_role');

Route::group(['prefix' => 'admin' , 'as' => 'admin.'], function() {

    Route::get('login', 'Auth\AdminAuthController@showLoginForm')->name('login');

    Route::post('login', 'Auth\AdminAuthController@login')->name('login.post');

    Route::get('logout', 'Auth\AdminAuthController@logout')->name('logout');

    Route::get('secure', 'AdminController@secure')->name('secure');

    // Registration Routes...

    Route::get('register', 'Auth\AdminAuthController@showRegistrationForm');

    Route::post('register', 'Auth\AdminAuthController@register');

    // Password Reset Routes...
    Route::get('password/reset/{token?}', 'Auth\AdminPasswordController@showResetForm');

    Route::post('password/email', 'Auth\AdminPasswordController@sendResetLinkEmail');

    Route::post('password/reset', 'Auth\AdminPasswordController@reset');

    Route::get('/payment/failure' , 'ApplicationController@payment_failure')->name('payment.failure');

    // Videos

    Route::get('/live_videos', 'AdminController@live_videos')->name('live-videos.index');

    Route::get('/live-videos/list', 'AdminController@live_videos_history')->name('live-videos.history');

    Route::get('/live-videos/view/{id}', 'AdminController@live_videos_view')->name('live-videos.view');

    Route::get('/live-videos/payments', 'AdminController@live_video_payments')->name('live-videos.payments');


    // Exports tables

    Route::get('/users/export/', 'AdminExportController@users_export')->name('users.export');

    Route::get('/channels/export/', 'AdminExportController@channels_export')->name('channels.export');

    Route::get('/videos/export/', 'AdminExportController@videos_export')->name('video_tapes.export');

    Route::get('/subscription/payment/export/', 'AdminExportController@subscription_export')->name('subscription.export');

    Route::get('/payperview/payment/export/', 'AdminExportController@payperview_export')->name('payperview.export');

    Route::get('/live-videos/export/', 'AdminExportController@livevideos_export')->name('live-videos.export');

    Route::get('/live-video/payment/export/', 'AdminExportController@livevideo_payment_export')->name('livevideo-payment.export');

    // Languages

    Route::get('/languages/index', 'LanguageController@languages_index')->name('languages.index'); 

    Route::get('/languages/download/', 'LanguageController@languages_download')->name('languages.download'); 

    Route::get('/languages/create', 'LanguageController@languages_create')->name('languages.create');
    
    Route::get('/languages/edit', 'LanguageController@languages_edit')->name('languages.edit');

    Route::get('/languages/status', 'LanguageController@languages_status_change')->name('languages.status');   

    Route::post('/languages/save', 'LanguageController@languages_save')->name('languages.save');

    Route::get('/languages/delete', 'LanguageController@languages_delete')->name('languages.delete');

    Route::get('/languages/set_default', 'LanguageController@languages_set_default')->name('languages.set_default');


    // ============= branch v4.0-admin-coderevamp ================

    Route::get('/', 'NewAdminController@dashboard')->name('dashboard');

    // New Admin user methods

    Route::get('/users/index', 'NewAdminController@users_index')->name('users.index');

    Route::get('/users/create', 'NewAdminController@users_create')->name('users.create');

    Route::get('/users/edit', 'NewAdminController@users_edit')->name('users.edit');
    
    Route::post('/users/save', 'NewAdminController@users_save')->name('users.save');

    Route::get('/users/view', 'NewAdminController@users_view')->name('users.view');

    Route::get('/users/delete', 'NewAdminController@users_delete')->name('users.delete');

    Route::get('/users/status','NewAdminController@users_status_change')->name('users.status');

    Route::get('/users/verify/', 'NewAdminController@users_verify_status')->name('users.verify');

    Route::get('/users/channels/', 'NewAdminController@users_channels')->name('users.channels');

    Route::get('/users/history/', 'NewAdminController@users_history')->name('users.history');

    Route::get('users/type/','NewAdminController@users_type_list')->name('users.type');

    Route::get('/users/history/delete/', 'NewAdminController@users_history_delete')->name('users.history.delete');

    Route::get('/users/wishlist/', 'NewAdminController@users_wishlist')->name('users.wishlist');

    Route::get('/users/wishlist/delete/', 'NewAdminController@users_wishlist_delete')->name('users.wishlist.delete');    

    Route::get('/users/playlist/index', 'NewAdminController@playlists_index')->name('users.playlist.index');
    
    Route::get('/users/playlist/delete', 'NewAdminController@playlists_delete')->name('users.playlist.delete');

    Route::get('/users/playlist/view', 'NewAdminController@playlist_video')->name('users.playlist.view'); 

    Route::get('/users/playlist/video/remove', 'NewAdminController@playlists_video_remove')->name('users.playlist.video.delete');
    
    Route::get('/users/referral/index', 'NewAdminController@users_index')->name('users.referral.index');

    //User Subscriptions

    Route::get('/users/subscriptions/', 'NewAdminController@users_subscriptions')->name('users.subscriptions.plans');

    Route::get('/users/subscriptions/save', 'NewAdminController@users_subscription_save')->name('users.subscription.save');

    // New Admin Channeles methods begins

    Route::get('/channels', 'NewAdminController@channels_index')->name('channels.index');

resources/views/new_admin/users/create.blade.php
@extends('layouts.admin')

@section('title', tr('add_user'))

@section('content-header', tr('add_user'))

@section('breadcrumb')
    <li><a href="{{route('admin.users.index')}}"><i class="fa fa-user"></i> {{tr('users')}}</a></li>
    <li class="active"><i class="fa fa-user-plus"></i> {{tr('add_user')}}</li>
@endsection

@section('styles')

<link rel="stylesheet" href="{{asset('admin-css/plugins/datepicker/datepicker3.css')}}">

@endsection

@section('content')

  @include('new_admin.users._form')

@endsection

@section('scripts')

<script src="{{asset('admin-css/plugins/datepicker/bootstrap-datepicker.js')}}"></script> 
<script src="{{asset('assets/js/jstz.min.js')}}"></script>

<script>
    
 var max_age_limit = "{{Setting::get('max_register_age_limit' , 18)}}";

max_age_limit = max_age_limit ? "-"+max_age_limit+"y" : "-15y";

$('#dob').datepicker({
    autoclose:true,
    format : 'dd-mm-yyyy',
    endDate: max_age_limit,
});


$(document).ready(function() {

    var dMin = new Date().getTimezoneOffset();
    var dtz = -(dMin/60);
    // alert(dtz);
    $("#userTimezone").val(jstz.determine().name());
});


function loadFile(event, id){
    // alert(event.files[0]);
    var reader = new FileReader();
    reader.onload = function(){
      var output = document.getElementById(id);
      // alert(output);
      output.src = reader.result;
      //$("#c4-header-bg-container .hd-banner-image").css("background-image", "url("+this.result+")");
    };
    reader.readAsDataURL(event.files[0]);
}

</script>

<script src="https://cdn.ckeditor.com/4.5.5/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'description' );
</script>

@endsection

resources/views/new_admin/users/history.blade.php
@extends('layouts.admin')

@section('title', tr('view_history'))

@section('content-header')

{{tr('view_history')}} - 

<a href="{{route('admin.users.view' ,['user_id' => $user_details->id] )}}">{{$user_details->name}}</a>

@endsection

@section('breadcrumb')
    <li><a href="{{route('admin.users.index')}}"><i class="fa fa-user"></i> {{tr('users')}}</a></li>
    <li class="active"> {{tr('view_history')}}</li>
@endsection

@section('content')

	<div class="row">
        
        <div class="col-xs-12">

        @include('notification.notify')

          	<div class="box">

	            <div class="box-body">

	            	@if(count($user_histories) > 0)

		              	<table id="example1" class="table table-bordered table-striped">

							<thead>
							    <tr>
							      <th>{{tr('id')}}</th>
							      <th>{{tr('username')}}</th>
							      <th>{{tr('video')}}</th>
							      <th>{{tr('date')}}</th>
							      <th>{{tr('action')}}</th>
							    </tr>
							</thead>

							<tbody>

								@foreach($user_histories as $i => $user_history_details)

								    <tr>
								      	<td>{{$i+1}}</td>

								      	<td>
								      		<a href="{{route('admin.users.view', ['user_id' => $user_history_details->user_id])}}" >{{$user_history_details->username}}</a>
								      	</td>
								      	
								      	<td>
								      		<a href="{{route('admin.video_tapes.view', ['video_tape_id' => $user_history_details->video_tape_id]) }}" >{{$user_history_details->title}}</a>
								      	</td>
								      	
								      	<td>{{$user_history_details->date}}</td>
									    
									    <td>
	            						
								            <a href="{{route('admin.users.history.delete' , ['history_id' => $user_history_details->user_history_id] )}}" onclick="return confirm(&quot;{{ tr('admin_user_history_delete_confirm', $user_history_details->title) }}&quot;)" class="btn btn-danger" title="{{tr('delete')}}" ><b><i class="fa fa-trash"></i></b> 
          									</a>
									    </td>
									    
								    </tr>					

								@endforeach
							</tbody>

						</table>

					@else
						<h3 class="no-result">{{tr('no_history_found')}}</h3>
					@endif

	            </div>


          	</div>

        </div>
    
    </div>

@endsection

resources/views/new_admin/users/index.blade.php
@extends('layouts.admin')

@section('title', tr('users'))

@section('content-header') 

{{ tr('users') }} 

<a href="#" id="help-popover" class="btn btn-danger" style="font-size: 14px;font-weight: 600" title="Any Help ?">{{ tr('help') }}</a>

<div id="help-content" style="display: none">

    <ul class="popover-list">
        <li><span class="text-green"><i class="fa fa-check-circle"></i></span>{{ tr('subscribed_user') }}</li>
        <li><span class="text-red"><i class="fa fa-times"></i></span>{{ tr('unsubscribed_user') }}</li>
        <li><b>{{ tr('redeems') }} - </b>{{ tr('current_wallet_amt') }}</li>
        <li><b>{{ tr('validity_days') }} - </b>{{ tr('expiry_date_subscription') }}</li>
    </ul>
    
</div>

@endsection

@section('breadcrumb')
    <li class="active"><i class="fa fa-user"></i> {{ tr('users') }}</li>
@endsection

@section('content')

	<div class="row">

        <div class="col-xs-12">
			
			@include('notification.notify')

          	<div class="box box-primary">

	          	<div class="box-header label-primary">
	                <b style="font-size:18px;">{{ tr('users') }}</b>

	                <a href="{{ route('admin.users.create') }}" class="btn btn-default pull-right">{{ tr('add_user') }}</a>

	                <!-- EXPORT OPTION START -->

						@if(count($users) > 0 )
		                
			                <ul class="admin-action btn btn-default pull-right" style="margin-right: 20px">
			                 	
								<li class="dropdown">
					                
					                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
					                  {{ tr('export') }} <span class="caret"></span>
					                </a>
					               
					                <ul class="dropdown-menu">
					                  	<li role="presentation">
					                  		<a role="menuitem" tabindex="-1" href="{{ route('admin.users.export' , ['format' => 'xlsx']) }}">
					                  			<span class="text-red"><b>{{ tr('excel_sheet') }}</b></span>
					                  		</a>
					                  	</li>

					                  	<li role="presentation">
					                  		<a role="menuitem" tabindex="-1" href="{{ route('admin.users.export' , ['format' => 'csv']) }}">
					                  			<span class="text-blue"><b>{{ tr('csv') }}</b></span>
					                  		</a>
					                  	</li>
					                </ul>
							
								</li>
							
							</ul>

						@endif

		            <!-- EXPORT OPTION END -->
	            </div>

	            <div class="box-body table-responsive">

	            	@if(count($users) > 0)

		              	<table id="example1" class="table table-bordered table-striped">

							<thead>
							    <tr>
							      <th>{{ tr('id') }}</th>
							      <th>{{ tr('username') }}</th>
							      <th>{{ tr('email') }}</th>
							      <th>{{ tr('channels') }}</th>
							      <th>{{ tr('videos') }}</th>
							      <th>{{ tr('plan_text') }}</th>
							      <th>{{ tr('redeems') }}</th>
							      @if(Setting::get('email_verify_control') == YES)
							      <th>{{ tr('user_is_verified') }}</th>
							      @endif
							      <th>{{ tr('status') }}</th>
							      <th>{{ tr('action') }}</th>
							    </tr>
							</thead>

							<tbody>
								
								@foreach($users as $i => $user_details)

								    <tr>
								      	<td>{{ $i+1 }}</td>

								      	<td>
								      		<a href="{{ route('admin.users.view' ,  ['user_id' => $user_details->id] ) }}"> 

								      			{{ $user_details->name }}

								      			@if($user_details->user_type)

								      			<span class="text-green pull-right"><i class="fa fa-check-circle"></i></span>

								      			@else

								      			<span class="text-red pull-right"><i class="fa fa-times"></i></span>

								      			@endif
								      		</a>
								      	</td>

								      	<td>{{ $user_details->email }}</td>
								      	
								      	<td class="text-center"><a target="_blank" href="{{ route('admin.users.channels' , ['user_id' => $user_details->id] ) }}">{{ $user_details->get_channel_count }}</a></td>

								      	<td class="text-center"><a target="_blank" href="{{ route('admin.video_tapes.index' , $user_details->id) }}">{{ $user_details->get_channel_videos_count }}</a></td>

										<td>
											@if($user_details->user_type)
												{{ get_expiry_days($user_details->id)['days'] }} days
											@endif
										</td>

								      	<td>
								      		<b>{{ formatted_amount($user_details->userRedeem ? $user_details->userRedeem->remaining : 0) }}</b>
								     	</td>

								      	@if(Setting::get('email_verify_control') == USER_EMAIL_VERIFIED)

									      	<td>
										      	@if(!$user_details->is_verified)
										      		<a href="{{ route('admin.users.verify' ,['user_id' => $user_details->id] ) }}" class="btn btn-xs btn-success">{{ tr('verify') }}</a>

										      	@else
										      		<span>{{ tr('verified') }}</span>
										      	@endif									      	
									      	</td>

								      	@endif

								      	<td>								      		
								      		@if($user_details->status == USER_APPROVED)
								      			<span class="label label-success">{{ tr('approved') }}</span>
								       		@else
								       			<span class="label label-warning">{{ tr('pending') }}</span>
								       		@endif
								      	</td>
								 
								      	<td>

	            							<ul class="admin-action btn btn-default">

	            								<li class="dropdown">									               
									                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
									                  {{ tr('action') }} <span class="caret"></span>
									                </a>

									                <ul class="dropdown-menu dropdown-menu-right">

									                <li role="presentation"></li>

									                  	<li role="presentation"><a role="menuitem" tabindex="-1" href="{{ route('admin.users.view' , ['user_id' => $user_details->id] ) }}">{{ tr('view') }}</a></li>
									                  
									                  	@if(Setting::get('admin_delete_control') == YES )

									               			@if(get_expiry_days($user_details->id) > 0)
									                  	 		<li role="presentation"><a role="menuitem" tabindex="-1" onclick="return confirm(&quot;{{tr('admin_user_delete_with_expiry_days_confirmation') }}&quot;);" href="javascript:;" > {{ tr('delete') }} </a></li>	
									                  		@else 
									                  			<li role="presentation">
									                  	 			<a role="menuitem" tabindex="-1" onclick="return confirm(&quot;{{ tr('admin_premium_user_delete_confirmation', $user_details->name ) }}&quot;);" href="javascript:;">{{ tr('delete') }}
									                  			</a></li>
									                  	 	@endif

									               		@else

									               			<li role="presentation"><a role="menuitem" tabindex="-1" href="{{ route('admin.users.edit' , ['user_id' => $user_details->id] ) }}">{{ tr('edit') }}</a></li>		           		
									                  	 	@if(get_expiry_days($user_details->id) > 0)
									                  	 		
									                  	 		<li role="presentation"><a role="menuitem" tabindex="-1" onclick="return confirm(&quot;{{ tr('admin_user_delete_with_expiry_days_confirmation' ) }}&quot;);" href="{{ route('admin.users.delete', ['user_id' => $user_details->id] ) }}"> {{ tr('delete') }} </a></li>	
									                  		@else 
									                  			<li role="presentation">
									                  	 			<a role="menuitem" tabindex="-1" onclick="return confirm(&quot;{{ tr('admin_premium_user_delete_confirmation', $user_details->name ) }}&quot;);" href="{{ route('admin.users.delete', ['user_id' => $user_details->id] ) }}">{{ tr('delete') }}
									                  			</a></li>
									                  	 	@endif

									                  	@endif

									                  	<li class="divider" role="presentation"></li>

									                  	@if($user_details->status == USER_APPROVED )
									                  		
									                  		<li role="presentation">

									                  			<a role="menuitem" tabindex="-1" href="{{ route('admin.users.status', ['user_id' => $user_details->id] ) }}" onclick="return confirm(&quot;{{ tr('admin_user_decline_confirmation', $user_details->name) }}&quot;)">
									                  				<span class="text-danger">{{ tr('decline') }}</span>
									                  			</a>
									                  		</li>
									                  	
									                  	@else
									                  	
									                  		<li role="presentation"><a role="menuitem"  tabindex="-1" href="{{ route('admin.users.status',['user_id' => $user_details->id] ) }}" onclick="return confirm(&quot;{{ tr('admin_user_approve_confirmation', $user_details->name) }}&quot;)" >
									                  			<span class="text-success">{{ tr('approve') }}</span></a></li>
									                  	@endif

									                  	<li class="divider" role="presentation"></li>

									                  	<li role="presentation">
									                  		<a role="menuitem" tabindex="-1" href="{{route('admin.users.subscriptions.plans' ,['user_id' => $user_details->id])}}">
									                  			{{ tr('plans') }}
									                  		</a>
									                  	</li>

									                  	<li role="presentation">
									                  		<a role="menuitem" tabindex="-1" href="{{ route('admin.users.playlist.index' , ['user_id' => $user_details->id] ) }}">
									                  			{{ tr('playlists') }}
									                  		</a>
									                  	</li>	
									                  	
									                </ul>

	              								</li>

	            							</ul>

								      	</td>

								    </tr>

								@endforeach

							</tbody>

						</table>

					@else
						<h3 class="no-result">{{ tr('no_user_found') }}</h3>
					@endif

	            </div>

          	</div>

        </div>

    </div>

@endsection

resources/views/new_admin/users/playlist_index.blade.php
@extends('layouts.admin')

@section('title', tr('playlist'))

@section('content-header') 

<a href="{{ route('admin.users.view',['user_id' => $user_details])}}" >{{ $user_details->name }}'s </a>- {{ tr('playlist') }} 

@endsection

@section('breadcrumb')

    <li><a href="{{ route('admin.users.index') }}"><i class="fa fa-user"></i> {{ tr('users') }}</a></li>
    
    <li><a href="{{ route('admin.users.view' , ['user_id' => $user_details->id] ) }}"><i class="fa fa-user"></i> {{ tr('view_user') }}</a></li>

    <li class="active"><i class="fa fa-user"></i> {{ tr('playlist') }}</li>

@endsection

@section('content')

	<div class="row">

        <div class="col-xs-12">
			
			@include('notification.notify')

          	<div class="box box-primary">

	          	<div class="box-header label-primary">
	                <b style="font-size:18px;">{{ tr('playlist') }}</b>
	            </div>

	            <div class="box-body table-responsive">

	            	@if(count($playlists) > 0)

		              	<table id="example1" class="table table-bordered table-striped">

							<thead>

							    <tr>

							      	<th>{{ tr('id') }}</th>

							      	<th style="display: none">{{ tr('channel') }}</th>

							      	<th>{{ tr('playlist') }}</th>

							      	<th>{{ tr('total_videos') }}</th>
							      
							      	<th>{{ tr('added_on') }}</th>

							      	<th>{{ tr('action') }}</th>

							    </tr>

							</thead>

							<tbody>

								@foreach($playlists as $i => $playlist_details)

								    <tr>
								      	<td>{{ $i+1 }}</td>

								      	<td style="display: none">
								      		@if($playlist_details->channel_name)
								      			<a href="{{ route('admin.channels.view' ,  ['channel_id' => $playlist_details->channel_id] ) }}">{{ $playlist_details->channel_name}}</a>
								      		@else
								      			-
								      		@endif
								      	</td>

								      	<td><a href="{{ route('admin.users.playlist.view' ,  ['playlist_id' => $playlist_details->playlist_id] ) }}">{{ $playlist_details->title }}</a></td>

								 		<td><a href="{{ route('admin.users.playlist.view' ,  ['playlist_id' => $playlist_details->playlist_id] ) }}"> {{ $playlist_details->total_videos }}</a>
								 		</td>								      	
								      	
								      	<td> {{ $playlist_details->created_at  }} </td>
								      	
								      	<td>

											@if(Setting::get('admin_delete_control') == YES )

	          									<a href="javascript:;" onclick="return confirm(&quot;{{ tr('admin_user_playlist_delete_confirmation',$playlist_details->title) }}&quot;)" class="btn btn-danger" title="{{tr('delete')}}" ><b><i class="fa fa-trash"></i></b> 
	          									</a>	

	          								@else

												<a href="{{ route('admin.users.playlist.delete', ['playlist_id' => $playlist_details->playlist_id] ) }}" onclick="return confirm(&quot;{{ tr('admin_user_playlist_delete_confirmation',$playlist_details->title) }}&quot;)" class="btn btn-danger" title="{{tr('delete')}}" ><b><i class="fa fa-trash"></i></b> 
	          									</a>

	          								@endif

	          								<a href="{{ route('admin.users.playlist.view' ,  ['playlist_id' => $playlist_details->playlist_id] ) }}" class="btn btn-primary" ><b><i class="fa fa-eye"></i></b> </a>

								      	</td>

								    </tr>

								@endforeach

							</tbody>

						</table>

					@else
						<h3 class="no-result">{{ tr('no_playlist_found') }}</h3>
					@endif

	            </div>

          	</div>

        </div>

    </div>

@endsection

resources/views/new_admin/users/wishlist.blade.php
@extends('layouts.admin')

@section('title', tr('view_wishlist'))

@section('content-header')

{{ tr('view_wishlist') }} - 

<a href="{{ route('admin.users.view' , ['user_id' => $user_details->id] ) }}">{{ $user_details->name }}</a>
@endsection

@section('breadcrumb')
     
    <li><a href="{{ route('admin.users.index') }}"><i class="fa fa-user"></i> {{ tr('users') }}</a></li>
    <li class="active"> {{ tr('view_wishlist') }}</li>
@endsection

@section('content')

	<div class="row">

        <div class="col-xs-12">
			
			@include('notification.notify')

	        <div class="box">

	            <div class="box-body">

	            	@if(count($user_wishlists) > 0)

		              	<table id="example1" class="table table-bordered table-striped">

							<thead>
							    <tr>
							      	<th>{{ tr('id') }}</th>
							      	<th>{{ tr('username') }}</th>
							      	<th>{{ tr('video') }}</th>
							      	<th>{{ tr('date') }}</th>
							      	<th>{{ tr('action') }}</th>
							    </tr>
							</thead>

							<tbody>

								@foreach($user_wishlists as $i => $user_wishlist_details)

								    <tr>
								      	<td>{{ $i+1 }}</td>

								      	<td>
								      		<a href="{{route('admin.users.view', ['user_id' => $user_wishlist_details->user_id])}}" >{{ $user_wishlist_details->username }}
								      		</a>
								      	</td>
								      	
								      	<td>
								      		<a href="{{route('admin.video_tapes.view', ['video_tape_id' => $user_wishlist_details->user_id])}}" > {{ $user_wishlist_details->title }}
								      		</a>
								      	</td>
								      	
								      	<td>{{ $user_wishlist_details->date }}</td>
									   
									    <td>
	            							<ul class="admin-action btn btn-default">
	            								
	            								<li class="dropup">
									                
									                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
									                  {{ tr('action') }} 
									                  <span class="caret"></span>
									                </a>

									                <ul class="dropdown-menu">
									                  	<li role="presentation"><a role="menuitem" tabindex="-1" onclick="return confirm(&nbps;{{ tr('admin_user_wishlist_delete_confirm',  $user_wishlist_details->title )}}&nbps;);" href="{{ route('admin.users.wishlist.delete' , $user_wishlist_details->wishlist_id) }}">{{ tr('delete_wishlist') }}</a></li>
									                </ul>

	              								</li>

	            							</ul>

									    </td>

								    </tr>					

								@endforeach

							</tbody>

						</table>

					@else
						<h3 class="no-result">{{ tr('no_wishlist_found') }}</h3>
					@endif

	            </div>

	        </div>

        </div>

    </div>

@endsection