app/Http/routes.php
    Route::get('/users/subscriptions/save', 'NewAdminController@users_subscription_save')->name('users.subscription.save');

    // New Admin Channeles methods begins

    Route::get('/channels', 'NewAdminController@channels_index')->name('channels.index');

    Route::get('/channels/create', 'NewAdminController@channels_create')->name('channels.create');

    Route::get('/channels/edit', 'NewAdminController@channels_edit')->name('channels.edit');    
    Route::post('/channels/save', 'NewAdminController@channels_save')->name('channels.save');

    Route::get('/channels/videos', 'NewAdminController@channels_videos')->name('channels.videos');

    Route::get('/channels/delete', 'NewAdminController@channels_delete')->name('channels.delete');

    Route::get('/channels/view', 'NewAdminController@channels_view')->name('channels.view');

    Route::get('/channels/status/change', 'NewAdminController@channels_status_change')->name('channels.status');

    Route::get('/channels/subscribers', 'NewAdminController@channels_subscribers')->name('channels.subscribers');

    Route::get('/channel/playlists/index', 'NewAdminController@channels_playlists_index')->name('channels.playlists.index');

    Route::get('/channel/playlists/create', 'NewAdminController@channels_playlists_create')->name('channels.playlists.create');

    Route::get('/channel/playlists/edit', 'NewAdminController@channels_playlists_edit')->name('channels.playlists.edit');

    Route::post('/channel/playlists/save', 'NewAdminController@channels_playlists_save')->name('channels.playlists.save');

    Route::get('/channel/playlists/view', 'NewAdminController@channels_playlists_view')->name('channels.playlists.view');

    Route::get('/channel/playlists/delete', 'NewAdminController@channels_playlists_delete')->name('channels.playlists.delete');

    Route::get('/channel/playlists/status', 'NewAdminController@channels_playlists_status')->name('channels.playlists.status.change');

    Route::get('/channel/playlist/video/remove', 'NewAdminController@channels_playlists_video_remove')->name('channels.playlist.video.delete');// 

    Route::get('playlist/videos', 'NewAdminController@playlist_videos')->name('playlists.videos');

    // Route::get('playlist/channels', 'NewAdminController@playlist_channels')->name('playlist.channels');

    // New Admin Channeles methods ends

    // New Admin Categories methods ends
    
    Route::get('/categories/index', 'NewAdminController@categories_index')->name('categories.index');

    Route::get('/categories/create', 'NewAdminController@categories_create')->name('categories.create');

    Route::get('/categories/edit', 'NewAdminController@categories_edit')->name('categories.edit');

    Route::post('/categories/save', 'NewAdminController@categories_save')->name('categories.save');

    Route::get('/categories/view', 'NewAdminController@categories_view')->name('categories.view');

    Route::get('/categories/delete', 'NewAdminController@categories_delete')->name('categories.delete');

    Route::get('/categories/status', 'NewAdminController@categories_status')->name('categories.status');

    Route::get('categories/videos', 'NewAdminController@categories_videos')->name('categories.videos');

    Route::get('categories/channels', 'NewAdminController@categories_channels')->name('categories.channels');

    // New Admin categories methods ends

    // New Admin tags methods begins

    Route::get('/tags', 'NewAdminController@tags_index')->name('tags.index');

    Route::post('/tags/save', 'NewAdminController@tags_save')->name('tags.save');

    Route::get('/tags/delete', 'NewAdminController@tags_delete')->name('tags.delete');

    Route::get('/tags/status', 'NewAdminController@tags_status_change')->name('tags.status');

    // Route::get('/tags/videos', 'NewAdminController@tags_videos')->name('tags.videos');
    
    Route::get('/tags/videos', 'NewAdminController@video_tapes_index')->name('tags.videos');

    // New Admin tags methods ends

    // New Admin coupons methods    

    Route::get('/coupons/index', 'NewAdminController@coupons_index')->name('coupons.index');

    Route::get('/coupons/create','NewAdminController@coupons_create')->name('coupons.create');

    Route::get('/coupons/edit','NewAdminController@coupons_edit')->name('coupons.edit');

    Route::post('/coupons/save','NewAdminController@coupons_save')->name('coupons.save');

    Route::get('/coupons/view', 'NewAdminController@coupons_view')->name('coupons.view');

    Route::get('/coupons/delete','NewAdminController@coupons_delete')->name('coupons.delete');

    Route::get('/coupon/status', 'NewAdminController@coupons_status_change')->name('coupons.status');

    // New Admin Coupons methods ends

    // New Admin AdsDetail methods begins

    Route::get('ads-details/index','NewAdminController@ads_details_index')->name('ads-details.index');
    
    Route::get('ads-details/create','NewAdminController@ads_details_create')->name('ads-details.create');

    Route::get('ads-details/edit','NewAdminController@ads_details_edit')->name('ads-details.edit');

    Route::post('ads-details/save','NewAdminController@ads_details_save')->name('ads-details.save');

    Route::get('ads-details/view','NewAdminController@ads_details_view')->name('ads-details.view');

    Route::get('ads-details/delete','NewAdminController@ads_details_delete')->name('ads-details.delete');

    Route::get('ads-details/status','NewAdminController@ads_details_status')->name('ads-details.status');

    // New Admin coupons methods ends
    
    // New Admin Account methods begins

    Route::get('help' , 'NewAdminController@help')->name('help');

    Route::get('/profile', 'NewAdminController@profile')->name('profile');

    Route::post('/profile/save', 'NewAdminController@profile_save')->name('profile.save');

    Route::post('/change/password', 'NewAdminController@change_password')->name('change.password');

    // New Admin Account methods ends

    // New Admin Pages methods begins

    Route::get('/pages', 'NewAdminController@pages_index')->name('pages.index');

    Route::get('/pages/edit/', 'NewAdminController@pages_edit')->name('pages.edit');

    Route::get('/pages/view/', 'NewAdminController@pages_view')->name('pages.view');

    Route::get('/pages/create', 'NewAdminController@pages_create')->name('pages.create');

    Route::post('/pages/create', 'NewAdminController@pages_save')->name('pages.save');

    Route::get('/pages/delete/', 'NewAdminController@pages_delete')->name('pages.delete');

    Route::get('/pages/status', 'NewAdminController@pages_status')->name('pages.status');

    // New Admin Pages methods ends


    // New Video CRUD start

    Route::get('/videos/create', 'NewAdminController@video_tapes_create')->name('video_tapes.create');

    Route::get('/videos/edit', 'NewAdminController@video_tapes_edit')->name('video_tapes.edit');

    Route::post('/videos/save', 'NewAdminController@video_tapes_save')->name('video_tapes.save');

    Route::get('/videos/images/{id}', 'NewAdminController@video_tapes_images')->name('video_tapes.images');

    Route::post('/videos/upload/image', 'NewAdminController@video_tapes_upload_image')->name('video_tapes.upload_image');

    Route::post('videos/save/default_img', 'NewAdminController@video_tapes_default_image_save')->name('video_tapes.save.default_img');

    Route::get('/videos/list', 'NewAdminController@video_tapes_index')->name('video_tapes.index');

    Route::get('/videos/view', 'NewAdminController@video_tapes_view')->name('video_tapes.view');

    Route::post('/videos/set-ppv/{id}', 'NewAdminController@video_tapes_set_ppv')->name('video_tapes.set-ppv');

    Route::get('/videos/delete', 'NewAdminController@video_tapes_delete')->name('video_tapes.delete');

    Route::get('/videos/status', 'NewAdminController@video_tapes_status')->name('video_tapes.status');

    Route::get('/videos/publish/{id}', 'NewAdminController@video_tapes_publish')->name('video_tapes.publish');

    Route::get('/videos/remove-ppv/{id}', 'NewAdminController@video_tapes_remove_ppv')->name('video_tapes.remove-ppv');

    Route::get('/videos/wishlist/{id}', 'NewAdminController@video_tapes_wishlist')->name('video_tapes.wishlist');

    Route::get('/videos/compression/complete','NewAdminController@video_tapes_compression_complete')->name('compress.status');

    // Spam Videos

    Route::get('/spam-videos', 'NewAdminController@spam_videos')->name('spam-videos');

    Route::get('/spam-videos/user-reports/{id}', 'NewAdminController@spam_videos_user_reports')->name('spam-videos.user-reports');

    Route::get('/spam/per-user-reports/{id}', 'AdminController@spam_videos_each_user_reports')->name('spam-videos.per-user-reports');

    Route::get('/unspam-video/{id}', 'AdminController@spam_videos_unspam')->name('spam-videos.unspam-video');

    // New Video CRUD end

    // New Admin Banner Ads methods begins   

    Route::get('banner-ads/index','NewAdminController@banner_ads_index')->name('banner_ads.index');

    Route::get('banner-ads/create','NewAdminController@banner_ads_create')->name('banner_ads.create');

    Route::get('banner-ads/edit','NewAdminController@banner_ads_edit')->name('banner_ads.edit');

    Route::post('banner-ads/save','NewAdminController@banner_ads_save')->name('banner_ads.save');

    Route::get('banner-ads/view','NewAdminController@banner_ads_view')->name('banner_ads.view');

    Route::get('banner-ads/delete','NewAdminController@banner_ads_delete')->name('banner_ads.delete');

    Route::get('banner-ads/status','NewAdminController@banner_ads_status_change')->name('banner_ads.status');

    Route::post('banner-ads/position','NewAdminController@banner_ads_position')->name('banner_ads.position');

    // New Admin Banner Ads methods ends

    // New Admin Banner Videos methods begins

    Route::get('/banner/videos', 'NewAdminController@banner_videos_index')->name('banner.videos.index');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    //
    public function videoTapeTags() {

        return $this->hasMany('App\VideoTapeTag');

    }

   /**
     * Boot function for using with User Events
     *
     * @return void
     */

    public static function boot()
    {
        //execute the parent's boot method 
        parent::boot();

        //delete your related models here, for example
        static::deleting(function($model)
        {

        	if (count($model->videoTapeTags) > 0) {

                foreach ($model->videoTapeTags as $key => $value) {

                   $value->delete();    

                }               

            }

        });

    }

}

app/VideoAd.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VideoAd extends Model
{
    //

    public function getVideoTape() {

        return $this->hasOne('App\VideoTape', 'id', 'video_tape_id');

    }

    public function getAd() {

        return $this->hasOne('App\AdsDetail', 'id', 'ad_id');

    }


    public function getAssignAds() {

        return $this->hasMany('App\AssignVideoAd', 'video_ad_id', 'id')->orderBy('video_time', 'asc');

    }



    public function getPreAdDetail() {

        return $this->hasOne('App\AssignVideoAd', 'video_ad_id', 'id')->where('ad_type', PRE_AD);

    }

    public function getPostAdDetail() {

        return $this->hasOne('App\AssignVideoAd', 'video_ad_id', 'id')->where('ad_type', POST_AD);

    }

    public function getBetweenAdDetails() {

        return $this->hasMany('App\AssignVideoAd', 'video_ad_id', 'id')->where('ad_type', BETWEEN_AD);

    }

    public function toArray()
    {
        $array = parent::toArray();

        $array['ad_details'] = $this->getAssignAds;

        $array['post_ad'] = $this->getPostAdDetail;

        $array['pre_ad'] = $this->getPreAdDetail;

        $array['between_ad'] = $this->getBetweenAdDetails;

        $array['ads_types'] = getTypeOfAds($this->types_of_ad);

        return $array;
    }


    /**
     * Boot function for using with User Events
     *
     * @return void
     */

    public static function boot()
    {
        //execute the parent's boot method 
        parent::boot();

        //delete your related models here, for example
        static::deleting(function($model)
        {
            if (count($model->getAssignAds) > 0) {

                foreach ($model->getAssignAds as $key => $value) {

                   $value->delete();    

                }               
             
            }

        }); 

    }

}

resources/views/admin/tags/index.blade.php
@extends('layouts.admin')

@section('title', tr('tags'))

@section('content-header', tr('tags'))

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li class="active"><i class="fa fa-tag"></i> {{tr('tags')}}</li>
@endsection

@section('content')

	@include('notification.notify')

	<div class="row">

        <div class="col-xs-12 text-right">        	

        	<button class="btn btn-success" type="button" onclick="$('#display_form').toggle()">{{tr('create_tag')}}</button>

        </div>

        <div class="col-xs-12" style="{{$model->id ? '' : 'display: none'}}" id="display_form">    

        	<div class="clearfix"></div>

        	<form action="{{route('admin.save.tag')}}" method="post" enctype="multipart/form-data">

        		<br>

        		<input type="hidden" name="id" value="{{$model->id}}">

        		<div class="row">

	        		<div class="col-xs-4">

	        		<input type="text" name="name" value="{{$model->name}}" required class="form-control" placeholder="{{tr('name')}}" pattern="[a-zA-Z]+" title="Enter only alphabets" maxlength="15"> 

	        		</div>

	        		<div class="col-xs-4">

	        		<input type="submit" name="button" value="{{tr('submit')}}" class="btn btn-success">

	        		</div>

        		</div>
        	

        	</form>

        </div>

    </div>

    <br>

	<div class="row">
        <div class="col-xs-12">        	
          <div class="box box-primary">

          	<div class="box-header label-primary">
                <b>{{tr('categories')}}</b>
            </div>
            
            <div class="box-body">

              	<table id="example1" class="table table-bordered table-striped">

					<thead>
					    <tr>
					      	<th>{{tr('id')}}</th>
					      	<th>{{tr('name')}}</th>
					      	<!-- <th>{{tr('count')}}</th> -->
					      	<th>{{tr('status')}}</th>
					      	<th>{{tr('action')}}</th>
					    </tr>
					</thead>

					<tbody>
					
						@foreach($datas as $i => $data)

						    <tr>
						      	<td>{{$i+1}}</td>
						      	<td class="text-capitalize">{{$data->name}}</td>
						      	<?php /*<td>{{$data->search_count}}</td>*/?>

						      
						      	<td class="text-center">

					      			@if($data->status)
						      			<span class="label label-success">{{tr('approved')}}</span>
						      		@else
						      			<span class="label label-warning">{{tr('pending')}}</span>
						      		@endif
						      	</td>

						      	

						      	<td class="text-center">
						      		
					      				<a href="{{route('admin.tags.index' ,['id'=>$data->id])}}" class="btn  btn-xs btn-primary" title="Edit">
				              				<i class="fa fa-edit"></i>
				              			</a>


						      			<a href="{{route('admin.tags.delete' ,['id'=>$data->id])}}" class="btn  btn-xs btn-danger" title="Delete" onclick="return confirm('Are you sure want to delete ?')">

				              				<i class="fa fa-trash"></i>

				              			</a>	

				              			<?php 

				              				$tag_approve_notes = tr('tag_approve_notes');

				              				$tag_decline_notes = tr('tag_decline_notes');
				              				

				              			?>

				              			@if($data->status)

				              				<a href="{{route('admin.tags.status' ,['id'=>$data->id])}}" class="btn  btn-xs btn-warning" title="Decline this Category"  onclick='return confirm("{{$tag_decline_notes}}")'>

					              				<i class="fa fa-times"></i>

					              			</a>


				              			@else

					              			<a href="{{route('admin.tags.status' ,['id'=>$data->id])}}" class="btn  btn-xs btn-success" title="Approve this Category" onclick='return confirm("{{$tag_approve_notes}}")'>

					              				<i class="fa fa-check"></i>

					              			</a>
				              			@endif

			              				<a href="{{route('admin.tags.videos' ,['tag_id'=>$data->id])}}" class="btn  btn-xs btn-success" title="Tagged Videos">

				              				<i class="fa fa-video-camera"></i>

				              			</a>
						      		
						      	</td>

						      	
						    </tr>
						@endforeach
					</tbody>
				
				</table>
			
            </div>
          </div>
        </div>
    </div>

@endsection



@section('scripts')

<!-- Add Js files and inline js here -->

<script type="text/javascript">
function loadFile(event, id){
    // alert(event.files[0]);
    var reader = new FileReader();
    reader.onload = function(){
      var output = document.getElementById(id);
      // alert(output);
      output.src = reader.result;
      //$("#c4-header-bg-container .hd-banner-image").css("background-image", "url("+this.result+")");
    };
    reader.readAsDataURL(event.files[0]);
}
</script>

@endsection

resources/views/admin/tags/videos.blade.php
@extends('layouts.admin')

@section('title', tr('videos'))

@section('content-header')

@if(isset($tag)) <span class="text-green"> "{{$tag->name}}" </span>- @endif {{tr('videos')}}

@endsection

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.tags')}}"><i class="fa fa-tag"></i>{{tr('tags')}}</a></li>
    <li class="active"><i class="fa fa-video-camera"></i> {{tr('videos')}}</li>
@endsection

@section('content')

    @include('notification.notify')
	<div class="row">
        <div class="col-xs-12">
          <div class="box box-primary">

          	<div class="box-header label-primary">
                <b style="font-size:18px;">{{tr('videos')}}</b>
                <a href="{{route('admin.video_tapes.create')}}" class="btn btn-default pull-right">{{tr('add_video')}}</a>
            </div>

            <div class="box-body">

            	@if(count($videos) > 0)

	              	<table id="example1" class="table table-bordered table-striped">

						<thead>

						    <tr>
								<th>{{tr('id')}}</th>
								<th>{{tr('channel')}}</th>
								<th>{{tr('category')}}</th>
								<th>{{tr('video_type')}}</th>
								<th>{{tr('title')}}</th>
								<th>{{tr('amount')}}</th>

								@if(Setting::get('is_payper_view'))
									<th>{{tr('ppv')}}</th>
								@endif
								<th>{{tr('is_ads')}}</th>

								<th>{{tr('status')}}</th>
								<th>{{tr('action')}}</th>
						    </tr>
						    
						</thead>

						<tbody>

							@foreach($videos as $i => $video)

							    <tr>
							      	
							      	<td><a href="{{route('admin.video_tapes.view' , ['id' => $video->video_tape_id] )}}">{{$i+1}}</a></td>
							      	
							      	<td><a href="{{route('admin.channels.view', ['channel_id' => $video->channel_id)}}">{{$video->channel_name}}</a></td>
							      		
							      	<td><a href="{{route('admin.categories.view', ['category_id'=>$video->category_id])}}" target="_blank">{{$video->category_name}}</a></td>

							      	<td>
							      		
							      		@if($video->video_type == VIDEO_TYPE_UPLOAD) 
                                            
                                            {{tr('manual_upload')}}

                                        @elseif($video->video_type == VIDEO_TYPE_YOUTUBE)

                                            {{tr('youtube_links')}}

                                        @else

                                            {{tr('other_links')}}

                                        @endif
							      	</td>
							      	<td><a href="{{route('admin.video_tapes.view' , array('id' => $video->video_tape_id))}}"> {{substr($video->title , 0,25)}}...</a></td>
							      	
							      	<td><b>{{Setting::get('currency')}} {{$video->admin_ppv_amount}}</b></td>

							      	@if(Setting::get('is_payper_view'))
							      	<td class="text-center">
							      		@if($video->ppv_amount > 0)
							      			<span class="label label-success">{{tr('yes')}}</span>
							      		@else
							      			<span class="label label-danger">{{tr('no')}}</span>
							      		@endif
							      	</td>
							      	@endif

							      	<td class="text-center">
							      		
							      		@if($video->ad_status)
							      			<span class="label label-success">{{tr('yes')}}</span>
							      		@else
							      			<span class="label label-danger">{{tr('no')}}</span>
							      		@endif

							      	</td>

							      	<td>
							      		@if ($video->compress_status == 0)
							      			<span class="label label-danger">{{tr('compress')}}</span>
							      		@else
								      		@if($video->is_approved)
								      			<span class="label label-success">{{tr('approved')}}</span>
								       		@else
								       			<span class="label label-warning">{{tr('pending')}}</span>
								       		@endif
								       	@endif
							      	</td>
								    <td>
            							<ul class="admin-action btn btn-default">
            								<li class="dropup">
								                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
								                  {{tr('action')}} <span class="caret"></span>
								                </a>
								                <ul class="dropdown-menu">
								                	@if ($video->compress_status == 1)
								                  	<li role="presentation">
                                                        @if(Setting::get('admin_delete_control'))
                                                            <a role="button" href="javascript:;" class="btn disabled" style="text-align: left">{{tr('edit')}}</a>
                                                        @else
                                                            <a role="menuitem" tabindex="-1" href="{{route('admin.video_tapes.edit' , array('id' => $video->video_tape_id))}}">{{tr('edit')}}</a>
                                                        @endif
                                                    </li>
                                                    @endif
								                  	<li role="presentation"><a role="menuitem" tabindex="-1" target="_blank" href="{{route('admin.video_tapes.view' , array('id' => $video->video_tape_id))}}">{{tr('view')}}</a></li>

								               		@if(Setting::get('is_payper_view'))

								                  		<li role="presentation">
								                  			<a role="menuitem" tabindex="-1" data-toggle="modal" data-target="#{{$video->video_tape_id}}">{{tr('pay_per_view')}}</a>
								                  		</li>

								                  	@endif

								                  	<li class="divider" role="presentation"></li>

								                  	@if($video->is_approved)
								                		<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.video_tapes.status',$video->video_tape_id)}}">{{tr('decline')}}</a></li>
								                	@else
								                		@if ($video->compress_status == 0)
								                			<li role="presentation"><a role="menuitem" tabindex="-1">{{tr('compress')}}</a></li>
								                		@else 
								                  			<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.video_tapes.status',$video->video_tape_id)}}">{{tr('approve')}}</a></li>
								                  		@endif
								                  	@endif

								                  	@if($video->publish_status == 0 && $video->compress_status == 1)
								                  		<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.video_tapes.publish',$video->video_tape_id)}}">{{tr('publish')}}</a></li>
								                  	@endif

								                  	@if ($video->compress_status == 1)
									                  	<li role="presentation">
									                  		@if(Setting::get('admin_delete_control'))

										                  	 	<a role="button" href="javascript:;" class="btn disabled" style="text-align: left">{{tr('delete')}}</a>

										                  	@else
									                  			<a role="menuitem" tabindex="-1" onclick="return confirm('Are you sure?')" href="{{route('admin.video_tapes.delete' , array('id' => $video->video_tape_id))}}">{{tr('delete')}}</a>
									                  		@endif
									                  	</li>
								                  	@endif

								                  	<li class="divider" role="presentation"></li>

								                  	@if($video->ad_status && !$video->getScopeVideoAds) 

								                  		<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.video_ads.create', array('video_tape_id'=>$video->video_tape_id))}}">{{tr('video_ad')}}</a></li>

								                  	@else

								                  		@if ($video->getScopeVideoAds)

								                  		<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.video-ads.view' , array('id' => $video->getScopeVideoAds->id))}}">{{tr('view_ad')}}</a></li>

								                  		@endif

								                  	@endif

								                  	<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.ads-details.ad-status-change',$video->video_tape_id)}}">{{ ($video->ad_status) ? tr('disable_ad') : tr('enable_ad')}}</a></li>

								                </ul>
              								</li>
            							</ul>
								    </td>
							    </tr>

							    <div id="{{$video->video_tape_id}}" class="modal fade" role="dialog">
								  <div class="modal-dialog">
								  <form action="{{route('admin.video_tapes.set-ppv', $video->video_tape_id)}}" method="POST">
									    <!-- Modal content-->
									   	<div class="modal-content">
									      <div class="modal-header">
									        <button type="button" class="close" data-dismiss="modal">&times;</button>
									        <h4 class="modal-title">{{tr('pay_per_view')}}</h4>
									      </div>
									      <div class="modal-body">
									        <div class="row">

									        	<input type="hidden" name="ppv_created_by" id="ppv_created_by" value="{{Auth::guard('admin')->user()->id}}">
									        	<div class="col-lg-3">
									        		<label>{{tr('type_of_user')}}</label>
									        	</div>
								                <div class="col-lg-9">
								                  <div class="input-group">
								                        <input type="radio" name="type_of_user" value="{{NORMAL_USER}}" {{($video->type_of_user == 0 || $video->type_of_user == '') ? 'checked' : (($video->type_of_user == NORMAL_USER) ? 'checked' : '')}}>&nbsp;<label>{{tr('normal_user')}}</label>&nbsp;
								                        <input type="radio" name="type_of_user" value="{{PAID_USER}}" {{($video->type_of_user == PAID_USER) ? 'checked' : ''}}>&nbsp;<label>{{tr('paid_user')}}</label>&nbsp;
								                        <input type="radio" name="type_of_user" value="{{BOTH_USERS}}" {{($video->type_of_user == BOTH_USERS) ? 'checked' : ''}}>&nbsp;<label>{{tr('both_user')}}</label>
								                  </div>
								                  <!-- /input-group -->
								                </div>
								            </div>
								            <br>
								            <div class="row">
									        	<div class="col-lg-3">
									        		<label>{{tr('type_of_subscription')}}</label>
									        	</div>
								                <div class="col-lg-9">
								                  <div class="input-group">
								                        <input type="radio" name="type_of_subscription" value="{{ONE_TIME_PAYMENT}}"  {{($video->type_of_subscription == 0 || $video->type_of_subscription == '') ? 'checked' : (($video->type_of_subscription == ONE_TIME_PAYMENT) ? 'checked' : '')}}>&nbsp;<label>{{tr('one_time_payment')}}</label>&nbsp;
								                        <input type="radio" name="type_of_subscription" value="{{RECURRING_PAYMENT}}" {{($video->type_of_subscription == RECURRING_PAYMENT) ? 'checked' : ''}}>&nbsp;<label>{{tr('recurring_payment')}}</label>
								                  </div>
								                  <!-- /input-group -->
								                </div>
								            </div>
								            <br>
								            <div class="row">
									        	<div class="col-lg-3">
									        		<label>{{tr('amount')}}</label>
									        	</div>
								                <div class="col-lg-9">
								                       <input type="number" required value="{{$video->ppv_amount}}" name="ppv_amount" class="form-control" id="amount" placeholder="{{tr('amount')}}" step="any" maxlength="6">
								                  <!-- /input-group -->
								                </div>
								            </div>
									      </div>
									      <div class="modal-footer">
									      	<div class="pull-left">
									      		@if($video->ppv_amount > 0)
									       			<a class="btn btn-danger" href="{{route('admin.video_tapes.remove-ppv', $video->video_tape_id)}}">{{tr('remove_pay_per_view')}}</a>
									       		@endif
									       	</div>
									        <div class="pull-right">
										        <button type="button" class="btn btn-default" data-dismiss="modal">{{tr('cancel')}}</button>
										        <button type="submit" class="btn btn-primary">{{tr('submit')}}</button>
										    </div>
										    <div class="clearfix"></div>
									      </div>
									    </div>
									</form>
								  </div>
								</div>
								<!-- Modal -->
								
							@endforeach
						</tbody>
					</table>
				@else
					<h3 class="no-result">{{tr('no_video_found')}}</h3>
				@endif
            </div>
          </div>
        </div>
    </div>

@endsection