app/Http/routes.php
Route::get('/user_session_language/{lang}', 'ApplicationController@set_session_language')->name('user_session_language');

Route::get('/user/searchall' , 'ApplicationController@search_video')->name('search');

Route::any('/user/search' , 'ApplicationController@search_all')->name('search-all');

// Social Login

Route::post('/social', array('as' => 'SocialLogin' , 'uses' => 'SocialAuthController@redirect'));

Route::get('/callback/{provider}', 'SocialAuthController@callback');

// Referral link generate

Route::get('/rc/{referral_code}', 'UserController@referrals_signup')->name('referrals_signup');

// Embed Links

Route::get('/embed', 'ApplicationController@embed_video')->name('embed_video');

// Admin to users login

Route::get('/master/login', 'UserController@master_login')->name('master.login');

// CRON

Route::get('/publish/video', 'ApplicationController@cron_publish_video')->name('publish');

Route::get('/notification/payment', 'ApplicationController@send_notification_user_payment')->name('notification.user.payment');

Route::get('/payment/expiry', 'ApplicationController@user_payment_expiry')->name('user.payment.expiry');

Route::get('cron_delete_video', 'ApplicationController@cron_delete_video');
    
// Static Pages

Route::get('/privacy', 'UserApiController@privacy')->name('user.privacy');

Route::get('/help', 'UserApiController@help')->name('user.help');

Route::get('/terms_condition', 'UserApiController@terms')->name('user.terms');

Route::get('/about', 'ApplicationController@about')->name('user.about');

Route::get('/privacy_policy', 'ApplicationController@privacy')->name('user.privacy_policy');

Route::get('/terms', 'ApplicationController@terms')->name('user.terms-condition');

Route::get('page_view/{id}', 'UserController@page_view')->name('page_view');

Route::get('/admin/check_role', 'NewAdminController@check_role');

Route::group(['prefix' => 'admin' , 'as' => 'admin.'], function() {

    Route::get('login', 'Auth\AdminAuthController@showLoginForm')->name('login');

    Route::post('login', 'Auth\AdminAuthController@login')->name('login.post');

    Route::get('logout', 'Auth\AdminAuthController@logout')->name('logout');

    Route::get('secure', 'AdminController@secure')->name('secure');

    // Registration Routes...

    Route::get('register', 'Auth\AdminAuthController@showRegistrationForm');

    Route::post('register', 'Auth\AdminAuthController@register');

    // Password Reset Routes...
    Route::get('password/reset/{token?}', 'Auth\AdminPasswordController@showResetForm');

    Route::post('password/email', 'Auth\AdminPasswordController@sendResetLinkEmail');

    Route::post('password/reset', 'Auth\AdminPasswordController@reset');

    Route::get('/payment/failure' , 'ApplicationController@payment_failure')->name('payment.failure');

    // Videos

    Route::get('/live_videos', 'AdminController@live_videos')->name('live-videos.index');

    Route::get('/live-videos/list', 'AdminController@live_videos_history')->name('live-videos.history');

    Route::get('/live-videos/view/{id}', 'AdminController@live_videos_view')->name('live-videos.view');

    Route::get('/live-videos/payments', 'AdminController@live_video_payments')->name('live-videos.payments');


    // Exports tables

    Route::get('/users/export/', 'AdminExportController@users_export')->name('users.export');

    Route::get('/channels/export/', 'AdminExportController@channels_export')->name('channels.export');

    Route::get('/videos/export/', 'AdminExportController@videos_export')->name('video_tapes.export');

    Route::get('/subscription/payment/export/', 'AdminExportController@subscription_export')->name('subscription.export');

    Route::get('/payperview/payment/export/', 'AdminExportController@payperview_export')->name('payperview.export');

    Route::get('/live-videos/export/', 'AdminExportController@livevideos_export')->name('live-videos.export');

    Route::get('/live-video/payment/export/', 'AdminExportController@livevideo_payment_export')->name('livevideo-payment.export');

    // Languages

    Route::get('/languages/index', 'LanguageController@languages_index')->name('languages.index'); 

    Route::get('/languages/download/', 'LanguageController@languages_download')->name('languages.download'); 

    Route::get('/languages/create', 'LanguageController@languages_create')->name('languages.create');
    
    Route::get('/languages/edit', 'LanguageController@languages_edit')->name('languages.edit');

    Route::get('/languages/status', 'LanguageController@languages_status_change')->name('languages.status');   

    Route::post('/languages/save', 'LanguageController@languages_save')->name('languages.save');

    Route::get('/languages/delete', 'LanguageController@languages_delete')->name('languages.delete');

    Route::get('/languages/set_default', 'LanguageController@languages_set_default')->name('languages.set_default');


    // ============= branch v4.0-admin-coderevamp ================

    Route::get('/', 'NewAdminController@dashboard')->name('dashboard');

    // New Admin user methods

    Route::get('/users/index', 'NewAdminController@users_index')->name('users.index');

    Route::get('/users/create', 'NewAdminController@users_create')->name('users.create');

    Route::get('/users/edit', 'NewAdminController@users_edit')->name('users.edit');
    
    Route::post('/users/save', 'NewAdminController@users_save')->name('users.save');

    Route::get('/users/view', 'NewAdminController@users_view')->name('users.view');

    Route::get('/users/delete', 'NewAdminController@users_delete')->name('users.delete');

    Route::get('/users/status','NewAdminController@users_status_change')->name('users.status');

    Route::get('/users/verify/', 'NewAdminController@users_verify_status')->name('users.verify');

    Route::get('/users/channels/', 'NewAdminController@users_channels')->name('users.channels');

    Route::get('/users/history/', 'NewAdminController@users_history')->name('users.history');

    Route::get('users/type/','NewAdminController@users_type_list')->name('users.type');

    Route::get('/users/history/delete/', 'NewAdminController@users_history_delete')->name('users.history.delete');

    Route::get('/users/wishlist/', 'NewAdminController@users_wishlist')->name('users.wishlist');

    Route::get('/users/wishlist/delete/', 'NewAdminController@users_wishlist_delete')->name('users.wishlist.delete');    

    Route::get('/users/playlist/index', 'NewAdminController@playlists_index')->name('users.playlist.index');
    
    Route::get('/users/playlist/delete', 'NewAdminController@playlists_delete')->name('users.playlist.delete');

    Route::get('/users/playlist/view', 'NewAdminController@playlist_video')->name('users.playlist.view'); 

    Route::get('/users/playlist/video/remove', 'NewAdminController@playlists_video_remove')->name('users.playlist.video.delete');
    
    Route::get('/users/referral/index', 'NewAdminController@users_index')->name('users.referral.index');

    //User Subscriptions

    Route::get('/users/subscriptions/', 'NewAdminController@users_subscriptions')->name('users.subscriptions.plans');

    Route::get('/users/subscriptions/save', 'NewAdminController@users_subscription_save')->name('users.subscription.save');

    // New Admin Channeles methods begins

    Route::get('/channels', 'NewAdminController@channels_index')->name('channels.index');

    Route::get('/channels/create', 'NewAdminController@channels_create')->name('channels.create');

    Route::get('/channels/edit', 'NewAdminController@channels_edit')->name('channels.edit');    
    Route::post('/channels/save', 'NewAdminController@channels_save')->name('channels.save');

    Route::get('/channels/videos', 'NewAdminController@channels_videos')->name('channels.videos');

    Route::get('/channels/delete', 'NewAdminController@channels_delete')->name('channels.delete');

    Route::get('/channels/view', 'NewAdminController@channels_view')->name('channels.view');

    Route::get('/channels/status/change', 'NewAdminController@channels_status_change')->name('channels.status');

    Route::get('/channels/subscribers', 'NewAdminController@channels_subscribers')->name('channels.subscribers');

    Route::get('/channel/playlists/index', 'NewAdminController@channels_playlists_index')->name('channels.playlists.index');

    Route::get('/channel/playlists/create', 'NewAdminController@channels_playlists_create')->name('channels.playlists.create');

    Route::get('/channel/playlists/edit', 'NewAdminController@channels_playlists_edit')->name('channels.playlists.edit');

    Route::post('/channel/playlists/save', 'NewAdminController@channels_playlists_save')->name('channels.playlists.save');

    Route::get('/channel/playlists/view', 'NewAdminController@channels_playlists_view')->name('channels.playlists.view');

    Route::get('/channel/playlists/delete', 'NewAdminController@channels_playlists_delete')->name('channels.playlists.delete');

    Route::get('/channel/playlists/status', 'NewAdminController@channels_playlists_status')->name('channels.playlists.status.change');

    Route::get('/channel/playlist/video/remove', 'NewAdminController@channels_playlists_video_remove')->name('channels.playlist.video.delete');// 

    Route::get('playlist/videos', 'NewAdminController@playlist_videos')->name('playlists.videos');

    // Route::get('playlist/channels', 'NewAdminController@playlist_channels')->name('playlist.channels');

    // New Admin Channeles methods ends

    // New Admin Categories methods ends
    
    Route::get('/categories/index', 'NewAdminController@categories_index')->name('categories.index');

    Route::get('/categories/create', 'NewAdminController@categories_create')->name('categories.create');

    Route::get('/categories/edit', 'NewAdminController@categories_edit')->name('categories.edit');

    Route::post('/categories/save', 'NewAdminController@categories_save')->name('categories.save');

app/Channel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Helpers\Helper;

class Channel extends Model
{
    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */

    public function scopeBaseResponse($query) {

        return $query->leftJoin('users', 'channels.user_id', '=', 'users.id')
                    ->select('channels.id as channel_id', 
                        'channels.user_id as user_id', 
                        'channels.name as channel_name', 
                        'channels.description as channel_description', 
                        'channels.picture as channel_image', 
                        'channels.cover as channel_cover', 
                        'users.name as channel_owner_name',
                        'users.picture as channel_owner_picture',
                        'channels.is_approved as is_admin_approved', 
                        'channels.status as channel_status', 
                        'channels.created_at', 
                        'channels.updated_at'
                    );

    }

    public function videoTape() {
        return $this->hasMany('App\VideoTape')->leftJoin('channels' , 'video_tapes.channel_id' , '=' , 'channels.id')->videoResponse();
    }

    /**
     * Get the video record associated with the flag.
     */
    public function getUser()
    {
        return $this->hasOne('App\User', 'id', 'user_id');
    }
    
    /**
     * Save the unique ID 
     *
     *
     */
    public function setUniqueIdAttribute($value){

        $this->attributes['unique_id'] = uniqid(str_replace(' ', '-', $value));

    }

    public function getVideos() {
        return $this->hasMany('App\VideoTape')->leftJoin('channels' , 'video_tapes.channel_id' , '=' , 'channels.id')->videoResponse()->where('status', DEFAULT_TRUE)->where('is_approved', DEFAULT_TRUE);
    }

    public function getVideoTape() {
        return $this->hasMany('App\VideoTape');
    }

    public function getChannelSubscribers() {
        return $this->hasMany('App\ChannelSubscription');
    }

    public function getPlaylist() {
        return $this->hasMany('App\Playlist');
    }

    public function getBellNotifications() {

         return $this->hasMany('App\BellNotification', 'channel_id', 'id');

    }

    /**
     * Boot function for using with User Events
     *
     * @return void
     */

    public static function boot()
    {
        //execute the parent's boot method 
        parent::boot();

        //delete your related models here, for example
        static::deleting(function($model)
        {

            if($model->picture) {
                Helper::delete_picture($model->picture, "/uploads/channels/picture/");
            }

            if($model->cover) {
                Helper::delete_picture($model->cover, "/uploads/channels/cover/");
            }

            if (count($model->getVideoTape) > 0) {

                foreach ($model->getVideoTape as $key => $value) {

                    Helper::delete_picture($value->video, "/uploads/videos/");

                    Helper::delete_picture($value->subtitle, "/uploads/subtitles/"); 

                    if ($value->banner_image) {

                        Helper::delete_picture($value->banner_image, "/uploads/images/");
                    }

                    Helper::delete_picture($value->default_image, "/uploads/images/");

                    if ($value->video_path) {

                        $explode = explode(',', $value->video_path);

                        if (count($explode) > 0) {

                            foreach ($explode as $key => $exp) {

                                Helper::delete_picture($exp, "/uploads/videos/");

                            }
                        }
                    }

                   $value->delete();    

                }

            }

            if (count($model->getChannelSubscribers) > 0) {

                foreach ($model->getChannelSubscribers as $key => $value) {

                   $value->delete();    

                }

            }

            if (count($model->getPlaylist) > 0) {

                foreach ($model->getPlaylist as $key => $playlist) {

                   $playlist->delete();    
                }
            }

            if (count($model->getBellNotifications) > 0) {

                foreach ($model->getBellNotifications as $key => $value) {

                   $value->delete();    

                }            

            }


        }); 

    }

}

resources/views/admin/channels/_form.blade.php
@include('notification.notify')

<div class="row">

    <div class="col-md-10">

        <div class="box box-primary">

            <div class="box-header label-primary">
                <b style="font-size:18px;">{{tr('add_channel')}}</b>
                <a href="{{route('admin.channels')}}" class="btn btn-default pull-right">{{tr('channels')}}</a>
            </div>

            <form class="form-horizontal" action="{{route('admin.channels.save')}}" method="POST" enctype="multipart/form-data" role="form">

                <div class="box-body">

                    <input type="hidden" name="channel_id" value="{{$channel->id}}">

                    <input type="hidden" name="user_id" value="{{$channel->user_id}}" >

                    <input type="hidden" name="device_type" value="{{DEVICE_WEB}}" >

                   
                    <div class="form-group">
                        <label for="name" class="col-sm-2 control-label">{{tr('user_name')}} *</label>
                        <div class="col-sm-10">
                            
                            @if(!$channel->id)
                            <select id="user_id" name="user_id" class="form-control select2" required data-placeholder="{{tr('select_user')}}*">
                                <option value="">{{tr('select_user_name')}}</option>
                                @foreach($users as $user)
                                    <option value="{{$user->id}}">{{$user->name}}</option>
                                @endforeach
                            </select>
                            @else

                                @foreach($users as $user)

                                    @if($user->id == $channel->user_id)

                                    <div class="col-sm-10"><span class="badge badge-succes" >{{$user->name}}</span></div>

                                    @endif

                                @endforeach

                            @endif
                           
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="name" class="col-sm-2 control-label">{{tr('name')}} *</label>
                        <div class="col-sm-10">
                            <input type="text" required class="form-control" id="name" name="name" placeholder="{{tr('channel_name')}}" minlength="6" title="Min length must be an 6 character" value="{{$channel->name}}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="description" class="col-sm-2 control-label">{{tr('description')}} *</label>
                        <div class="col-sm-10">
                            <textarea required class="form-control" id="description" name="description" placeholder="{{tr('description')}}" required>{{$channel->description}}</textarea> 
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="picture" class="col-sm-2 control-label">{{tr('picture')}} *</label>
                        <div class="col-sm-10">

                            <input type="file" accept="image/png, image/jpeg" id="picture" name="picture" placeholder="{{tr('picture')}}" @if(!$channel->id) required @endif>
                            <p class="help-block">{{tr('image_validate')}} {{tr('image_square')}}</p>
                            @if($channel->picture)
                                <img style="height: 90px;margin-bottom: 15px; border-radius:2em;" src="{{$channel->picture}}">
                            @endif
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="cover" class="col-sm-2 control-label">{{tr('cover')}} *</label>
                        <div class="col-sm-10">
                            <input type="file" accept="image/png, image/jpeg" id="cover" name="cover" placeholder="{{tr('cover')}}" @if(!$channel->id) required @endif>
                            <p class="help-block">{{tr('image_validate')}} {{tr('rectangle_image')}}</p>
                            @if($channel->cover)
                                <img style="height: 90px;margin-bottom: 15px; border-radius:2em;" src="{{$channel->cover}}">
                            @endif
                        </div>
                    </div>

                </div>

                <div class="box-footer">
                    <a href="" class="btn btn-danger">{{tr('reset')}}</a>
                    <button type="submit" class="btn btn-success pull-right">{{tr('submit')}}</button>
                </div>
            </form>
        
        </div>

    </div>

</div>


@section('scripts')
    <script src="https://cdn.ckeditor.com/4.5.5/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'description' );
    </script>
@endsection

resources/views/admin/channels/create.blade.php
@extends('layouts.admin')

@section('title', tr('add_channel'))

@section('content-header', tr('add_channel'))

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.channels')}}"><i class="fa fa-suitcase"></i> {{tr('channels')}}</a></li>
    <li class="active">{{tr('add_channel')}}</li>
@endsection


@section('content')

@include('admin.channels._form')

@endsection

resources/views/admin/channels/edit.blade.php
@extends('layouts.admin')

@section('title', tr('edit_channel'))

@section('content-header', tr('edit_channel'))

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.channels')}}"><i class="fa fa-suitcase"></i> {{tr('channels')}}</a></li>
    <li class="active">{{tr('edit_channel')}}</li>
@endsection

@section('content')

@include('admin.channels._form')

@endsection

resources/views/admin/channels/list.blade.php
@extends('layouts.admin')

@section('title', tr('channels'))

@section('content-header')

@if(isset($user)) <span class="text-green"> {{$user->name}} </span>- @endif {{tr('channels')}}

@endsection

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li class="active"><i class="fa fa-suitcase"></i> {{tr('channels')}}</li>
@endsection

@section('content')

	@include('notification.notify')

	<div class="row">
        <div class="col-xs-12">
          <div class="box box-primary">
          	<div class="box-header label-primary">
                <b style="font-size:18px;">{{tr('channels')}}</b>
                <a href="{{route('admin.channels.create')}}" class="btn btn-default pull-right">{{tr('add_channel')}}</a>

                <!-- EXPORT OPTION START -->

	          	@if(count($channels) > 0 )
	                  
	            <ul class="admin-action btn btn-default pull-right" style="margin-right: 20px">        
	            	<li class="dropdown">
	                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
	                      {{tr('export')}} <span class="caret"></span>
	                    </a>

	                    <ul class="dropdown-menu">
	                        <li role="presentation">
	                          <a role="menuitem" tabindex="-1" href="{{route('admin.channels.export' , ['format' => 'xls'])}}">
	                            <span class="text-red"><b>{{tr('excel_sheet')}}</b></span>
	                          </a>
	                        </li>

	                        <li role="presentation">
	                          <a role="menuitem" tabindex="-1" href="{{route('admin.channels.export' , ['format' => 'csv'])}}">
	                            <span class="text-blue"><b>{{tr('csv')}}</b></span>
	                          </a>
	                        </li>
	                    </ul>
	              	</li>
	            </ul>

	          @endif

              <!-- EXPORT OPTION END -->

            </div>
            <div class="box-body table-responsive">

            	@if(count($channels) > 0)

	              	<table id="example1" class="table table-bordered table-striped">

						<thead>
						    <tr>
						      <th>{{tr('id')}}</th>
						      <th>{{tr('channel')}}</th>
						      <th>{{tr('user_name')}}</th>
						      <th>{{tr('no_of_videos')}}</th>
						      <th>{{tr('subscribers')}}</th>
						      <th>{{tr('amount')}}</th>
						      <th>{{tr('status')}}</th>
						      <th>{{tr('action')}}</th>
						    </tr>
						</thead>

						<tbody>
							@foreach($channels as $i => $channel)
							 
							    <tr>
							      	<td>{{$i+1}}</td>
							      	
							      	<td><a target="_blank" href="{{route('admin.channels.view', $channel->id)}}">{{$channel->name}}</a></td>
							      
							      	<td><a target="_blank" href="{{route('admin.users.view', $channel->user_id)}}">{{$channel->getUser ? $channel->getUser->name : ''}}</a></td>
							      	
							      	<td><a target="_blank" href="{{route('admin.channels.videos', array('id'=> $channel->id))}}">{{$channel->get_video_tape_count}}</a></td>
	                            	
	                            	<td><a target="_blank" href="{{route('admin.channels.subscribers', array('id'=> $channel->id))}}">{{$channel->get_channel_subscribers_count}}</a></td>

	                            	<td>{{ formatted_amount(getAmountBasedChannel($channel->id))}}</td>

								    <td>
								      		@if($channel->is_approved)
								      			<span class="label label-success">{{tr('approved')}}</span>
								       		@else
								       			<span class="label label-warning">{{tr('pending')}}</span>
								       		@endif
								    </td>
							     	<td>
            							<ul class="admin-action btn btn-default">
            								
            								<li class="{{$i <=2 ? 'dropdown' : 'dropup'}}">
            								
								                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
								                  {{tr('action')}} <span class="caret"></span>
								                </a>
								                <ul class="dropdown-menu">
								                  	<li role="presentation">
                                                        @if(Setting::get('admin_delete_control'))
                                                            <a role="button" href="javascript:;" class="btn disabled" style="text-align: left">{{tr('edit')}}</a>
                                                        @else
                                                            <a role="menuitem" tabindex="-1" href="{{route('admin.channels.edit' , array('id' => $channel->id))}}">{{tr('edit')}}</a>
                                                        @endif
                                                    </li>		
                                                    
													<li class="divider" role="presentation"></li>

								                  	<li role="presentation">

									                  	@if(Setting::get('admin_delete_control'))

										                  	<a role="button" href="javascript:;" class="btn disabled" style="text-align: left">{{tr('delete')}}</a>

										                @else

								                  			<a role="menuitem" tabindex="-1" onclick="return confirm('Are you sure?')" href="{{route('admin.channels.delete' , array('channel_id' => $channel->id))}}">{{tr('delete')}}</a>
								                  		@endif
								                  	</li>

													<li class="divider" role="presentation"></li>

													<?php 

								                  		$channel_approve_notes = tr('channel_approve_notes');

								                  		$channel_decline_notes = tr('channel_decline_notes');

								                  	?>

								                  	@if($channel->is_approved)
								                  		<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.channel.approve' , array('id' => $channel->id , 'status' =>0))}}" onclick='return confirm("{{$channel_decline_notes}}")'>{{tr('decline')}}</a></li>
								                  	@else
								                  		<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.channel.approve' , array('id' => $channel->id , 'status' => 1))}}" onclick='return confirm("{{$channel_approve_notes}}")'>{{tr('approve')}}</a></li>
								                  	@endif

								                </ul>
              								</li>
            							</ul>
							      </td>
							    </tr>
							@endforeach
						</tbody>
					</table>
				@else
					<h3 class="no-result">{{tr('no_result_found')}}</h3>
				@endif
            </div>
          </div>
        </div>
    </div>

@endsection

resources/views/admin/channels/subscribers.blade.php
@extends('layouts.admin')

@section('title', tr('channels'))

@section('content-header')

@if(isset($user)) <span class="text-green"> {{$user->name}} </span>- @endif {{tr('channels')}}

@endsection

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.channels')}}"><i class="fa fa-suitcase"></i> {{tr('channels')}}</a></li>
    <li class="active"><i class="fa fa-suitcase"></i> {{tr('subscribers')}}</li>
@endsection

@section('content')

	@include('notification.notify')

	<div class="row">
        <div class="col-xs-12">
          <div class="box box-primary">
          	<div class="box-header label-primary">
                <b style="font-size:18px;">{{tr('subscribers')}}</b>
            </div>
            <div class="box-body">

            	@if(count($subscribers) > 0)

	              	<table id="example1" class="table table-bordered table-striped">

						<thead>
						    <tr>
						      <th>{{tr('id')}}</th>
						      <th>{{tr('channel')}}</th>
						      <th>{{tr('picture')}}</th>
						      <th>{{tr('subscriber_name')}}</th>
						  	  <th>{{tr('action')}}</th>
						    </tr>
						</thead>

						<tbody>
							@foreach($subscribers as $i => $subscriber)

							    <tr>
							      	<td>{{$i+1}}</td>
							      	<td><a target="_blank" href="{{route('admin.channels.view', $subscriber->channel_id)}}">{{$subscriber->getChannel ? $subscriber->getChannel->name : ''}}</a></td>
							      	
							      	<td>
							      		@if($subscriber->getChannel)
	                                	<img style="height: 30px;" src="{{$subscriber->getChannel->picture}}">
	                                	@endif
	                            	</td>	                           

	                            	<td>{{$subscriber->getUser ? $subscriber->getUser->name : ''}}</a></td>

	                            	
							     	<td>	

							     		@if($subscriber->getUser)

							     		<a href="{{route('admin.users.view', $subscriber->getUser ? $subscriber->getUser-> id: '')}}" class="btn btn-success">{{tr('view_user')}}</a>
							     		@else

							     			-

							     		@endif
            							
							      	</td>
							    </tr>
							@endforeach
						</tbody>
					</table>
				@else
					<h3 class="no-result">{{tr('no_result_found')}}</h3>
				@endif
            </div>
          </div>
        </div>
    </div>

@endsection